(self.AMP=self.AMP||[]).push({n:"amp-animation",v:"1524862012167",f:(function(AMP){var t;function C(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var k=Object.getOwnPropertyDescriptor(b,d);k&&Object.defineProperty(a,d,k)}else a[d]=b[d]}function aa(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ba=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function ca(a){var b=Object.create(null);if(!a)return b;for(var c;c=ba.exec(a);){var d=aa(c[1],c[1]),k=c[2]?aa(c[2],c[2]):"";b[d]=k}return b};var da="";function ea(){var a,b=a||self;if(!b.AMP_MODE){var c=b,d=ca(c.location.originalHash||c.location.hash),k=ca(c.location.search);da||(da=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"011524862012167");b.AMP_MODE={localDev:!1,development:!("1"!=d.development&&!c.AMP_DEV_MODE),examiner:"2"==d.development,filter:d.filter,geoOverride:d["amp-geo"],minified:!0,lite:void 0!=k.amp_lite,test:!1,log:d.log,version:"1524862012167",rtvVersion:da}}};var fa=Object.prototype.toString;self.log=self.log||{user:null,dev:null,userForEmbed:null};var ga=self.log;function I(){if(!ga.user)throw Error("failed to call initLogConstructor");return ga.user}function ha(){if(ga.dev)return ga.dev;throw Error("failed to call initLogConstructor");};function ia(a){var b=Object.create(null);a&&Object.assign(b,a);return b};function ja(a){this.Ma=a;this.J=Object.create(null)}ja.prototype.get=function(a){if(this.J[a])return this.J[a].access=Date.now(),this.J[a].payload};ja.prototype.put=function(a,b){var c=this;this.J[a]={payload:b,access:Date.now()};var d=Object.keys(this.J);d.length>this.Ma&&(ha().warn("lru-cache","Trimming template cache"),d.sort(function(a,b){return c.J[b].access-c.J[a].access}),delete this.J[d[d.length-1]])};function ka(a,b){return b.toUpperCase()}function la(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function oa(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var pa,qa;
function ra(a){var b;pa||(pa=self.document.createElement("a"),qa=self.UrlCache||(self.UrlCache=new ja(100)));var c=qa.get(a);if(c)return c;var d=pa;d.href=a;d.protocol||(d.href=d.href);var k={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==k.pathname[0]&&(k.pathname="/"+k.pathname);if("http:"==k.protocol&&80==k.port||"https:"==k.protocol&&443==k.port)k.port="",k.host=k.hostname;k.origin=d.origin&&
"null"!=d.origin?d.origin:"data:"!=k.protocol&&k.host?k.protocol+"//"+k.host:k.href;var m=k,q=m;if(b)return q;qa.put(a,q);return q}function sa(a){"string"==typeof a&&(a=ra(a));return"https:"==a.protocol||"localhost"==a.hostname||la(a.hostname,".localhost")};function ta(a,b){try{return JSON.parse(a)}catch(c){b&&b(c)}};function ua(a,b){a=a.__AMP_TOP||a;return va(a,b)}function wa(a,b){a=xa(a);a=xa(a);a=a.isSingleDoc()?a.win:a;return va(a,b)}function ya(a,b){var c=(a.ownerDocument||a).defaultView;if(a=c&&c!=b)a=c,a=(a.__AMP_TOP||a)==b;if(a)try{return c.frameElement}catch(d){}return null}function xa(a){return a.nodeType?ua((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}
function va(a,b){var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function za(a,b){for(var c,d=a;d&&d!==c;d=d.parentElement)if(b(d))return d;return null}function Aa(a,b){return a.closest?a.closest(b):za(a,function(a){return Ba(a,b)})}function Ba(a,b){var c=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return c?c.call(a,b):!1}var Ca;
function Ga(a){if(null==Ca){var b=a.ownerDocument;try{var c=b.createElement("div"),d=b.createElement("div");c.appendChild(d);Ca=c.querySelector(":scope div")===d}catch(k){Ca=!1}}Ca?a=a.querySelector(":scope > script"):(a.classList.add("i-amphtml-scoped"),b=a.querySelector(".i-amphtml-scoped > script"),a.classList.remove("i-amphtml-scoped"),a=b);return a};var Ha,Ia="Webkit webkit Moz moz ms O o".split(" ");function Ja(a,b,c){if(oa(b,"--"))return b;Ha||(Ha=ia());var d=Ha[b];if(!d||c){d=b;if(void 0===a[b]){var k=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var m=0;m<Ia.length;m++){var q=Ia[m]+k;if(void 0!==a[q]){k=q;break a}}k=""}var w=k;void 0!==a[w]&&(d=w)}c||(Ha[b]=d)}return d}function Ka(a,b){for(var c in b){var d=a,k=b[c],m=Ja(d.style,c,void 0);m&&(d.style[m]=k)}};var La;function Ma(a,b){function c(a){try{return m(a)}catch(u){throw self.reportError(u),u;}}var d=void 0,k=a,m=b,q=Na(),w=!1;d&&(w=d.capture);k.addEventListener("resize",c,q?d:w)}function Na(){if(void 0!==La)return La;La=!1;try{var a={get capture(){La=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return La};function Oa(a,b){Ma(a,b)};function Pa(){this.C=null}t=Pa.prototype;t.add=function(a){var b=this;this.C||(this.C=[]);this.C.push(a);return function(){b.remove(a)}};t.remove=function(a){this.C&&(a=this.C.indexOf(a),-1<a&&this.C.splice(a,1))};t.removeAll=function(){this.C&&(this.C.length=0)};t.fire=function(a){if(this.C)for(var b=this.C,c=0;c<b.length;c++)(0,b[c])(a)};t.getHandlerCount=function(){return this.C?this.C.length:0};function Ra(a){var b=0,c=1;return Math.min(Math.max(a,b),c)};var Sa=/^(data|https)\:/i,Ta=2*Math.PI/360,Ua=Math.PI/200,Va=/(calc|var|url|rand|index|width|height|num)\(/i,Wa=/\d(%|em|rem|vw|vh|vmin|vmax|s|deg|grad)/i,Xa=/^(infinity|infinite)$/i;function R(){}R.prototype.css=function(){};R.prototype.resolve=function(a,b){return this.isConst(b)?this:this.calc(a,b)};R.prototype.isConst=function(){return!0};R.prototype.calc=function(){return this};function Ya(a){this.h=a}C(Ya,R);Ya.prototype.css=function(){return this.h};function Za(a){this.I=a||[]}C(Za,R);
Za.prototype.css=function(){return this.I.map(function(a){return a.css()}).join(" ")};Za.prototype.isConst=function(a){return this.I.reduce(function(b,c){return b&&c.isConst(a)},!0)};Za.prototype.calc=function(a,b){for(var c=[],d=0;d<this.I.length;d++){var k=this.I[d].resolve(a,b);if(k)c.push(k);else return null}return new Za(c)};function $a(a){this.da=a}C($a,R);$a.prototype.css=function(){return this.da?'url("'+this.da+'")':""};$a.prototype.isConst=function(){return!this.da||Sa.test(this.da)};
$a.prototype.calc=function(a){a=a.resolveUrl(this.da);return new Ya('url("'+a+'")')};function V(a,b,c){this.ca=a;this.l=b;this.j=c.toLowerCase()}C(V,R);t=V.prototype;t.css=function(){return""+this.l+this.j};t.createSameUnits=function(){};t.isConst=function(a){return a?this.isNorm():!0};t.isNorm=function(){return!0};t.norm=function(){return this};t.calc=function(a,b){return b?this.norm(a):this};t.calcPercent=function(){throw Error("cannot calculate percent for "+this.ca);};
function X(a){V.call(this,"NUM",a,"")}C(X,V);X.prototype.createSameUnits=function(a){return new X(a)};function ab(a){V.call(this,"PRC",a,"%")}C(ab,V);ab.prototype.createSameUnits=function(a){return new ab(a)};ab.prototype.isNorm=function(){return!1};ab.prototype.norm=function(a){return a.getDimension()?(new Y(0,"px")).calcPercent(this.l,a):this};function Y(a,b){V.call(this,"LEN",a,b)}C(Y,V);Y.prototype.createSameUnits=function(a){return new Y(a,this.j)};Y.prototype.isNorm=function(){return"px"==this.j};
Y.prototype.norm=function(a){if(this.isNorm())return this;if("em"==this.j||"rem"==this.j){var b="em"==this.j?a.getCurrentFontSize():a.getRootFontSize();return new Y(this.l*b,"px")}if("vw"==this.j||"vh"==this.j||"vmin"==this.j||"vmax"==this.j){var c=a.getViewportSize(),d=c.width*this.l/100,k=c.height*this.l/100;a=0;"vw"==this.j?a=d:"vh"==this.j?a=k:"vmin"==this.j?a=Math.min(d,k):"vmax"==this.j&&(a=Math.max(d,k));return new Y(a,"px")}throw bb(this.j);};
Y.prototype.calcPercent=function(a,b){var c=b.getDimension();b=b.getCurrentElementSize();var d=cb(c,b);return new Y(d*a/100,"px")};function Z(a,b){V.call(this,"ANG",a,b)}C(Z,V);Z.prototype.createSameUnits=function(a){return new Z(a,this.j)};Z.prototype.isNorm=function(){return"rad"==this.j};Z.prototype.norm=function(){if(this.isNorm())return this;if("deg"==this.j)return new Z(this.l*Ta,"rad");if("grad"==this.j)return new Z(this.l*Ua,"rad");throw bb(this.j);};
function db(a,b){V.call(this,"TME",a,b)}C(db,V);db.prototype.createSameUnits=function(a){return new db(a,this.j)};db.prototype.isNorm=function(){return"ms"==this.j};db.prototype.norm=function(){return this.isNorm()?this:new db(eb(this),"ms")};function eb(a){if("ms"==a.j)return a.l;if("s"==a.j)return 1E3*a.l;throw bb(a.j);}function fb(a,b,c){this.za=a.toLowerCase();this.fa=b;this.ka=c||null}C(fb,R);
fb.prototype.css=function(){var a=this.fa.map(function(a){return a.css()}).join(",");return this.za+"("+a+")"};fb.prototype.isConst=function(a){return this.fa.reduce(function(b,c){return b&&c.isConst(a)},!0)};
fb.prototype.calc=function(a,b){for(var c=[],d={},k=0;k<this.fa.length;d={node:d.node},k++){d.node=this.fa[k];var m=void 0;if(m=this.ka&&k<this.ka.length?a.withDimension(this.ka[k],function(c){return function(){return c.node.resolve(a,b)}}(d)):d.node.resolve(a,b))c.push(m);else return null}return new fb(this.za,c)};function gb(a,b){fb.call(this,"translate"+a.toUpperCase(),b,""==a?["w","h"]:"x"==a?["w"]:"y"==a?["h"]:"z"==a?["z"]:"3d"==a?["w","h","z"]:null);this.$a=a}C(gb,fb);
function hb(a,b,c){this.S=a;this.Fa=b||null;this.Wa=c||null}C(hb,R);hb.prototype.css=function(){throw Error("no css");};hb.prototype.isConst=function(){return!1};hb.prototype.calc=function(a){a=this.Fa?a.getElementSize(this.Fa,this.Wa):a.getCurrentElementSize();return new Y(cb(this.S,a),"px")};function ib(a){this.Za=a}C(ib,R);ib.prototype.css=function(){throw Error("no css");};ib.prototype.isConst=function(){return!1};
ib.prototype.calc=function(a,b){a=this.Za.resolve(a,b);if(null==a)return null;a=a instanceof V?a.l:parseFloat(a.css());return null==a||isNaN(a)?null:new X(a)};function jb(a,b){this.K=void 0===a?null:a;this.M=void 0===b?null:b}C(jb,R);jb.prototype.css=function(){throw Error("no css");};jb.prototype.isConst=function(){return!1};
jb.prototype.calc=function(a,b){if(null==this.K||null==this.M)return new X(Math.random());var c=this.K.resolve(a,b);b=this.M.resolve(a,b);if(null==c||null==b)return null;if(!(c instanceof V&&b instanceof V))throw Error("left and right must be both numerical");if(c.ca!=b.ca)throw Error("left and right must be the same type");c.j!=b.j&&(c=c.norm(a),b=b.norm(a));var d=Math.random();return c.createSameUnits(Math.min(c.l,b.l)*(1-d)+Math.max(c.l,b.l)*d)};function pb(){}C(pb,R);
pb.prototype.css=function(){throw Error("no css");};pb.prototype.isConst=function(){return!1};pb.prototype.calc=function(a){return new X(a.getCurrentIndex())};function qb(a,b){this.Ia=a;this.ha=b||null}C(qb,R);qb.prototype.css=function(){return"var("+this.Ia+(this.ha?","+this.ha.css():"")+")"};qb.prototype.isConst=function(){return!1};qb.prototype.calc=function(a,b){var c=a.getVar(this.Ia);return c?c.resolve(a,b):this.ha?this.ha.resolve(a,b):null};function rb(a){this.xa=a}C(rb,R);
rb.prototype.css=function(){return"calc("+this.xa.css()+")"};rb.prototype.isConst=function(){return!1};rb.prototype.calc=function(a,b){return this.xa.resolve(a,b)};function sb(a,b,c){this.K=a;this.M=b;this.W=c}C(sb,R);sb.prototype.css=function(){return this.K.css()+" "+this.W+" "+this.M.css()};sb.prototype.isConst=function(){return!1};
sb.prototype.calc=function(a,b){var c=this.K.resolve(a,b);b=this.M.resolve(a,b);if(null==c||null==b)return null;if(!(c instanceof V&&b instanceof V))throw Error("left and right must be both numerical");if(c.ca!=b.ca)if(c instanceof ab)c=b.calcPercent(c.l,a);else if(b instanceof ab)b=c.calcPercent(b.l,a);else throw Error("left and right must be the same type");c.j!=b.j&&(c=c.norm(a),b=b.norm(a));var d="+"==this.W?1:-1;return c.createSameUnits(c.l+d*b.l)};
function tb(a,b,c){this.K=a;this.M=b;this.W=c}C(tb,R);tb.prototype.css=function(){return this.K.css()+" "+this.W+" "+this.M.css()};tb.prototype.isConst=function(){return!1};
tb.prototype.calc=function(a,b){var c=this.K.resolve(a,b);a=this.M.resolve(a,b);if(null==c||null==a)return null;if(!(c instanceof V&&a instanceof V))throw Error("left and right must be both numerical");var d;if("*"==this.W)if(c instanceof X)d=c.l,c=a;else{if(!(a instanceof X))throw Error("one of sides in multiplication must be a number");d=a.l}else{if(!(a instanceof X))throw Error("denominator must be a number");d=1/a.l}a=c.l*d;return isFinite(a)?c.createSameUnits(a):null};
function bb(a){return Error("unknown units: "+a)}function cb(a,b){return"w"==a?b.width:"h"==a?b.height:0};function ub(a,b){var c=a.styleSheets;if(!c)return null;a=(a.ownerDocument||a).defaultView;for(var d=c.length-1;0<=d;d--){var k;k=c[d];var m=b;if(k.cssRules){var q=k.ownerNode;k=q&&(q.hasAttribute("amp-custom")||q.hasAttribute("amp-keyframes"))?vb(a,k.cssRules,m):null}else k=null;if(k)return k}return null}
function vb(a,b,c){for(var d=b.length-1;0<=d;d--){var k=b[d];if(7==k.type){var m=k;if(k.name==c&&wb(a,k)){a=m;c=[];for(d=0;d<a.cssRules.length;d++){var q=a.cssRules[d],k={};k.offset="from"==q.keyText?0:"to"==q.keyText?1:parseFloat(q.keyText)/100;for(var q=q.style,w=0;w<q.length;w++){var g=q[w],u=g;la(g,"animation-timing-function")&&(u="easing");k[u]=q[g]}c.push(k)}return c}}else if(4==k.type||12==k.type){var A=vb(a,k.cssRules,c);if(A)return A}}return null}
function wb(a,b){if(b.media&&b.media.mediaText){var c=a.matchMedia(b.media.mediaText).matches;if(!c)return!1}return 12!=b.type||a.CSS&&a.CSS.supports&&a.CSS.supports(b.conditionText)?b.parentRule?wb(a,b.parentRule):!0:!1};var xb=function(){function a(a,f,b){var h;b=b||{};for(h=a.length;h--;b[a[h]]=f);return b}function b(){this.yy={}}var c=[1,7],d=[1,8],k=[1,9],m=[1,14],q=[1,15],w=[1,24],g=[1,25],u=[1,26],A=[1,27],n=[1,28],l=[1,29],r=[1,30],e=[1,31],f=[1,32],h=[1,33],z=[1,34],y=[1,35],p=[1,36],x=[1,37],E=[1,38],D=[1,39],G=[1,40],B=[1,41],F=[1,55],W=[1,42],H=[1,45],J=[1,46],S=[1,47],T=[1,48],N=[1,49],M=[1,50],K=[1,51],O=[1,52],U=[1,53],P=[1,54],L=[1,43],Q=[1,44],kb=[5,9,10,11,16,17,18,19,20,21,22,23,24,25,26,27,28,29,
30,31,32,33,34,35,44,48,49,50,51,52,53,54,55,57,58,59,60,62],v=[5,9,10,11,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,44,45,47,48,49,50,51,52,53,54,55,57,58,59,60,62,65,66,67,68],ma=[1,62],Da=[1,85],Ea=[1,86],lb=[1,87],mb=[1,88],Fa=[45,65,66,67,68],na=[1,91],nb=[45,47],ob=[45,67,68],Qa={trace:function hc(){},yy:{},Xa:{error:2,result:3,value:4,EOF:5,literal_or_function:6,literal:7,"function":8,STRING:9,NUMBER:10,PERCENTAGE:11,length:12,angle:13,time:14,url:15,HEXCOLOR:16,IDENT:17,LENGTH_PX:18,
LENGTH_EM:19,LENGTH_REM:20,LENGTH_VH:21,LENGTH_VW:22,LENGTH_VMIN:23,LENGTH_VMAX:24,LENGTH_CM:25,LENGTH_MM:26,LENGTH_Q:27,LENGTH_IN:28,LENGTH_PC:29,LENGTH_PT:30,ANGLE_DEG:31,ANGLE_RAD:32,ANGLE_GRAD:33,TIME_MS:34,TIME_S:35,var_function:36,calc_function:37,translate_function:38,dim_function:39,num_function:40,rand_function:41,index_function:42,any_function:43,FUNCTION_START:44,")":45,args:46,",":47,URL_START:48,TRANSLATE_START:49,TRANSLATE_X_START:50,TRANSLATE_Y_START:51,TRANSLATE_Z_START:52,TRANSLATE_3D_START:53,
WIDTH_START:54,HEIGHT_START:55,CLOSEST_START:56,NUM_START:57,RAND_START:58,INDEX_START:59,VAR_START:60,VAR_NAME:61,CALC_START:62,calc_expr:63,"(":64,"*":65,"/":66,"+":67,"-":68,$accept:0,$end:1},aa:{2:"error",5:"EOF",9:"STRING",10:"NUMBER",11:"PERCENTAGE",16:"HEXCOLOR",17:"IDENT",18:"LENGTH_PX",19:"LENGTH_EM",20:"LENGTH_REM",21:"LENGTH_VH",22:"LENGTH_VW",23:"LENGTH_VMIN",24:"LENGTH_VMAX",25:"LENGTH_CM",26:"LENGTH_MM",27:"LENGTH_Q",28:"LENGTH_IN",29:"LENGTH_PC",30:"LENGTH_PT",31:"ANGLE_DEG",32:"ANGLE_RAD",
33:"ANGLE_GRAD",34:"TIME_MS",35:"TIME_S",44:"FUNCTION_START",45:")",47:",",48:"URL_START",49:"TRANSLATE_START",50:"TRANSLATE_X_START",51:"TRANSLATE_Y_START",52:"TRANSLATE_Z_START",53:"TRANSLATE_3D_START",54:"WIDTH_START",55:"HEIGHT_START",56:"CLOSEST_START",57:"NUM_START",58:"RAND_START",59:"INDEX_START",60:"VAR_START",61:"VAR_NAME",62:"CALC_START",64:"(",65:"*",66:"/",67:"+",68:"-"},Da:[0,[3,2],[3,1],[4,1],[4,2],[6,1],[6,1],[7,1],[7,1],[7,1],[7,1],[7,1],[7,1],[7,1],[7,1],[7,1],[12,1],[12,1],[12,
1],[12,1],[12,1],[12,1],[12,1],[12,1],[12,1],[12,1],[12,1],[12,1],[12,1],[13,1],[13,1],[13,1],[14,1],[14,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[43,2],[43,3],[46,1],[46,3],[15,3],[38,3],[38,3],[38,3],[38,3],[38,3],[39,2],[39,2],[39,3],[39,3],[39,5],[39,5],[40,3],[41,2],[41,5],[42,2],[36,3],[36,5],[37,3],[63,1],[63,3],[63,3],[63,3],[63,3],[63,3]],performAction:function ic(a,f,b,h,c,e){var g=e.length-1;switch(c){case 1:return e[g-1];case 2:return null;case 3:case 5:case 6:case 10:case 11:case 12:case 13:case 34:case 35:case 36:case 37:case 38:case 39:case 40:case 41:case 65:this.c=
e[g];break;case 4:var p=e[g-1];e=e[g];g=p instanceof Za?p:new Za([p]);e instanceof Za?g.I=g.I.concat(e.I):g.I.push(e);this.c=g;break;case 7:case 14:case 15:this.c=new Ya(e[g]);break;case 8:this.c=new X(parseFloat(e[g]));break;case 9:this.c=new ab(parseFloat(e[g]));break;case 16:this.c=new Y(parseFloat(e[g]),"px");break;case 17:this.c=new Y(parseFloat(e[g]),"em");break;case 18:this.c=new Y(parseFloat(e[g]),"rem");break;case 19:this.c=new Y(parseFloat(e[g]),"vh");break;case 20:this.c=new Y(parseFloat(e[g]),
"vw");break;case 21:this.c=new Y(parseFloat(e[g]),"vmin");break;case 22:this.c=new Y(parseFloat(e[g]),"vmax");break;case 23:this.c=new Y(parseFloat(e[g]),"cm");break;case 24:this.c=new Y(parseFloat(e[g]),"mm");break;case 25:this.c=new Y(parseFloat(e[g]),"q");break;case 26:this.c=new Y(parseFloat(e[g]),"in");break;case 27:this.c=new Y(parseFloat(e[g]),"pc");break;case 28:this.c=new Y(parseFloat(e[g]),"pt");break;case 29:this.c=new Z(parseFloat(e[g]),"deg");break;case 30:this.c=new Z(parseFloat(e[g]),
"rad");break;case 31:this.c=new Z(parseFloat(e[g]),"grad");break;case 32:this.c=new db(parseFloat(e[g]),"ms");break;case 33:this.c=new db(parseFloat(e[g]),"s");break;case 42:this.c=new fb(e[g-1].slice(0,-1),[]);break;case 43:this.c=new fb(e[g-2].slice(0,-1),e[g-1]);break;case 44:this.c=[e[g]];break;case 45:p=e[g-2];p.push(e[g]);this.c=p;break;case 46:this.c=new $a(e[g-1].slice(1,-1));break;case 47:this.c=new gb("",e[g-1]);break;case 48:this.c=new gb("x",e[g-1]);break;case 49:this.c=new gb("y",e[g-
1]);break;case 50:this.c=new gb("z",e[g-1]);break;case 51:this.c=new gb("3d",e[g-1]);break;case 52:this.c=new hb("w");break;case 53:this.c=new hb("h");break;case 54:this.c=new hb("w",e[g-1].slice(1,-1));break;case 55:this.c=new hb("h",e[g-1].slice(1,-1));break;case 56:this.c=new hb("w",e[g-2].slice(1,-1),"closest");break;case 57:this.c=new hb("h",e[g-2].slice(1,-1),"closest");break;case 58:this.c=new ib(e[g-1]);break;case 59:this.c=new jb;break;case 60:this.c=new jb(e[g-3],e[g-1]);break;case 61:this.c=
new pb;break;case 62:this.c=new qb(e[g-1]);break;case 63:this.c=new qb(e[g-3],e[g-1]);break;case 64:this.c=new rb(e[g-1]);break;case 66:this.c=e[g-1];break;case 67:this.c=new tb(e[g-2],e[g],"*");break;case 68:this.c=new tb(e[g-2],e[g],"/");break;case 69:this.c=new sb(e[g-2],e[g],"+");break;case 70:this.c=new sb(e[g-2],e[g],"-")}},table:[{3:1,4:2,5:[1,3],6:4,7:5,8:6,9:c,10:d,11:k,12:10,13:11,14:12,15:13,16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,25:e,26:f,27:h,28:z,29:y,30:p,31:x,32:E,33:D,34:G,
35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,48:W,49:H,50:J,51:S,52:T,53:N,54:M,55:K,57:O,58:U,59:P,60:L,62:Q},{1:[3]},{5:[1,56],6:57,7:5,8:6,9:c,10:d,11:k,12:10,13:11,14:12,15:13,16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,25:e,26:f,27:h,28:z,29:y,30:p,31:x,32:E,33:D,34:G,35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,48:W,49:H,50:J,51:S,52:T,53:N,54:M,55:K,57:O,58:U,59:P,60:L,62:Q},{1:[2,2]},a(kb,[2,3]),a(v,[2,5]),a(v,[2,6]),a(v,[2,7]),a(v,[2,8]),a(v,[2,9]),a(v,[2,10]),
a(v,[2,11]),a(v,[2,12]),a(v,[2,13]),a(v,[2,14]),a(v,[2,15]),a(v,[2,34]),a(v,[2,35]),a(v,[2,36]),a(v,[2,37]),a(v,[2,38]),a(v,[2,39]),a(v,[2,40]),a(v,[2,41]),a(v,[2,16]),a(v,[2,17]),a(v,[2,18]),a(v,[2,19]),a(v,[2,20]),a(v,[2,21]),a(v,[2,22]),a(v,[2,23]),a(v,[2,24]),a(v,[2,25]),a(v,[2,26]),a(v,[2,27]),a(v,[2,28]),a(v,[2,29]),a(v,[2,30]),a(v,[2,31]),a(v,[2,32]),a(v,[2,33]),{9:[1,58]},{61:[1,59]},{6:61,7:5,8:6,9:c,10:d,11:k,12:10,13:11,14:12,15:13,16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,25:e,26:f,
27:h,28:z,29:y,30:p,31:x,32:E,33:D,34:G,35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,48:W,49:H,50:J,51:S,52:T,53:N,54:M,55:K,57:O,58:U,59:P,60:L,62:Q,63:60,64:ma},{6:64,7:5,8:6,9:c,10:d,11:k,12:10,13:11,14:12,15:13,16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,25:e,26:f,27:h,28:z,29:y,30:p,31:x,32:E,33:D,34:G,35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,46:63,48:W,49:H,50:J,51:S,52:T,53:N,54:M,55:K,57:O,58:U,59:P,60:L,62:Q},{6:64,7:5,8:6,9:c,10:d,11:k,12:10,13:11,14:12,15:13,
16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,25:e,26:f,27:h,28:z,29:y,30:p,31:x,32:E,33:D,34:G,35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,46:65,48:W,49:H,50:J,51:S,52:T,53:N,54:M,55:K,57:O,58:U,59:P,60:L,62:Q},{6:64,7:5,8:6,9:c,10:d,11:k,12:10,13:11,14:12,15:13,16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,25:e,26:f,27:h,28:z,29:y,30:p,31:x,32:E,33:D,34:G,35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,46:66,48:W,49:H,50:J,51:S,52:T,53:N,54:M,55:K,57:O,58:U,59:P,60:L,62:Q},
{6:64,7:5,8:6,9:c,10:d,11:k,12:10,13:11,14:12,15:13,16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,25:e,26:f,27:h,28:z,29:y,30:p,31:x,32:E,33:D,34:G,35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,46:67,48:W,49:H,50:J,51:S,52:T,53:N,54:M,55:K,57:O,58:U,59:P,60:L,62:Q},{6:64,7:5,8:6,9:c,10:d,11:k,12:10,13:11,14:12,15:13,16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,25:e,26:f,27:h,28:z,29:y,30:p,31:x,32:E,33:D,34:G,35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,46:68,48:W,49:H,50:J,
51:S,52:T,53:N,54:M,55:K,57:O,58:U,59:P,60:L,62:Q},{9:[1,70],45:[1,69],56:[1,71]},{9:[1,73],45:[1,72],56:[1,74]},{6:75,7:5,8:6,9:c,10:d,11:k,12:10,13:11,14:12,15:13,16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,25:e,26:f,27:h,28:z,29:y,30:p,31:x,32:E,33:D,34:G,35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,48:W,49:H,50:J,51:S,52:T,53:N,54:M,55:K,57:O,58:U,59:P,60:L,62:Q},{6:77,7:5,8:6,9:c,10:d,11:k,12:10,13:11,14:12,15:13,16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,25:e,26:f,27:h,28:z,
29:y,30:p,31:x,32:E,33:D,34:G,35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,45:[1,76],48:W,49:H,50:J,51:S,52:T,53:N,54:M,55:K,57:O,58:U,59:P,60:L,62:Q},{45:[1,78]},{6:64,7:5,8:6,9:c,10:d,11:k,12:10,13:11,14:12,15:13,16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,25:e,26:f,27:h,28:z,29:y,30:p,31:x,32:E,33:D,34:G,35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,45:[1,79],46:80,48:W,49:H,50:J,51:S,52:T,53:N,54:M,55:K,57:O,58:U,59:P,60:L,62:Q},{1:[2,1]},a(kb,[2,4]),{45:[1,81]},{45:[1,
82],47:[1,83]},{45:[1,84],65:Da,66:Ea,67:lb,68:mb},a(Fa,[2,65]),{6:61,7:5,8:6,9:c,10:d,11:k,12:10,13:11,14:12,15:13,16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,25:e,26:f,27:h,28:z,29:y,30:p,31:x,32:E,33:D,34:G,35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,48:W,49:H,50:J,51:S,52:T,53:N,54:M,55:K,57:O,58:U,59:P,60:L,62:Q,63:89,64:ma},{45:[1,90],47:na},a(nb,[2,44]),{45:[1,92],47:na},{45:[1,93],47:na},{45:[1,94],47:na},{45:[1,95],47:na},a(v,[2,52]),{45:[1,96]},{9:[1,97]},a(v,[2,53]),{45:[1,
98]},{9:[1,99]},{45:[1,100]},a(v,[2,59]),{47:[1,101]},a(v,[2,61]),a(v,[2,42]),{45:[1,102],47:na},a(v,[2,46]),a(v,[2,62]),{6:103,7:5,8:6,9:c,10:d,11:k,12:10,13:11,14:12,15:13,16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,25:e,26:f,27:h,28:z,29:y,30:p,31:x,32:E,33:D,34:G,35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,48:W,49:H,50:J,51:S,52:T,53:N,54:M,55:K,57:O,58:U,59:P,60:L,62:Q},a(v,[2,64]),{6:61,7:5,8:6,9:c,10:d,11:k,12:10,13:11,14:12,15:13,16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,
25:e,26:f,27:h,28:z,29:y,30:p,31:x,32:E,33:D,34:G,35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,48:W,49:H,50:J,51:S,52:T,53:N,54:M,55:K,57:O,58:U,59:P,60:L,62:Q,63:104,64:ma},{6:61,7:5,8:6,9:c,10:d,11:k,12:10,13:11,14:12,15:13,16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,25:e,26:f,27:h,28:z,29:y,30:p,31:x,32:E,33:D,34:G,35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,48:W,49:H,50:J,51:S,52:T,53:N,54:M,55:K,57:O,58:U,59:P,60:L,62:Q,63:105,64:ma},{6:61,7:5,8:6,9:c,10:d,11:k,12:10,
13:11,14:12,15:13,16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,25:e,26:f,27:h,28:z,29:y,30:p,31:x,32:E,33:D,34:G,35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,48:W,49:H,50:J,51:S,52:T,53:N,54:M,55:K,57:O,58:U,59:P,60:L,62:Q,63:106,64:ma},{6:61,7:5,8:6,9:c,10:d,11:k,12:10,13:11,14:12,15:13,16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,25:e,26:f,27:h,28:z,29:y,30:p,31:x,32:E,33:D,34:G,35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,48:W,49:H,50:J,51:S,52:T,53:N,54:M,55:K,57:O,58:U,
59:P,60:L,62:Q,63:107,64:ma},{45:[1,108],65:Da,66:Ea,67:lb,68:mb},a(v,[2,47]),{6:109,7:5,8:6,9:c,10:d,11:k,12:10,13:11,14:12,15:13,16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,25:e,26:f,27:h,28:z,29:y,30:p,31:x,32:E,33:D,34:G,35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,48:W,49:H,50:J,51:S,52:T,53:N,54:M,55:K,57:O,58:U,59:P,60:L,62:Q},a(v,[2,48]),a(v,[2,49]),a(v,[2,50]),a(v,[2,51]),a(v,[2,54]),{45:[1,110]},a(v,[2,55]),{45:[1,111]},a(v,[2,58]),{6:112,7:5,8:6,9:c,10:d,11:k,12:10,13:11,
14:12,15:13,16:m,17:q,18:w,19:g,20:u,21:A,22:n,23:l,24:r,25:e,26:f,27:h,28:z,29:y,30:p,31:x,32:E,33:D,34:G,35:B,36:16,37:17,38:18,39:19,40:20,41:21,42:22,43:23,44:F,48:W,49:H,50:J,51:S,52:T,53:N,54:M,55:K,57:O,58:U,59:P,60:L,62:Q},a(v,[2,43]),{45:[1,113]},a(Fa,[2,67]),a(Fa,[2,68]),a(ob,[2,69],{65:Da,66:Ea}),a(ob,[2,70],{65:Da,66:Ea}),a(Fa,[2,66]),a(nb,[2,45]),{45:[1,114]},{45:[1,115]},{45:[1,116]},a(v,[2,63]),a(v,[2,56]),a(v,[2,57]),a(v,[2,60])],defaultActions:{3:[2,2],56:[2,1]},parseError:function jc(a,
f){if(f.recoverable)this.trace(a);else throw a=Error(a),a.hash=f,a;},parse:function kc(a){function f(a){e.length-=2*a;h.length-=a;c.length-=a}var b=this,e=[0],g=[],h=[null],c=[],p=this.table,n="",l=0,y=0,r=0,d=2,G=1,z=c.slice.call(arguments,1),x=Object.create(this.lexer),u={yy:{}},k;for(k in this.yy)Object.prototype.hasOwnProperty.call(this.yy,k)&&(u.yy[k]=this.yy[k]);x.setInput(a,u.yy);u.yy.lexer=x;u.yy.parser=this;"undefined"==typeof x.yylloc&&(x.yylloc={});var A=x.yylloc;c.push(A);var E=x.options&&
x.options.ranges;this.parseError="function"===typeof u.yy.parseError?u.yy.parseError:Object.getPrototypeOf(this).parseError;var U=function(){var a;a=x.lex()||G;"number"!==typeof a&&(a=b.Xa[a]||a);return a};for(var B,m,D,q,F={},L,v,P,w;;){D=e[e.length-1];if(this.defaultActions[D])q=this.defaultActions[D];else{if(null===B||"undefined"==typeof B)B=U();q=p[D]&&p[D][B]}if("undefined"===typeof q||!q.length||!q[0]){var Q="";w=[];for(L in p[D])this.aa[L]&&L>d&&w.push("'"+this.aa[L]+"'");Q=x.showPosition?
"Parse error on line "+(l+1)+":\n"+x.showPosition()+"\nExpecting "+w.join(", ")+", got '"+(this.aa[B]||B)+"'":"Parse error on line "+(l+1)+": Unexpected "+(B==G?"end of input":"'"+(this.aa[B]||B)+"'");this.parseError(Q,{text:x.match,token:this.aa[B]||B,line:x.yylineno,loc:A,expected:w})}if(q[0]instanceof Array&&1<q.length)throw Error("Parse Error: multiple actions possible at state: "+D+", token: "+B);switch(q[0]){case 1:e.push(B);h.push(x.yytext);c.push(x.yylloc);e.push(q[1]);B=null;m?(B=m,m=null):
(y=x.yyleng,n=x.yytext,l=x.yylineno,A=x.yylloc,0<r&&r--);break;case 2:v=this.Da[q[1]][1];F.c=h[h.length-v];F.ta={first_line:c[c.length-(v||1)].first_line,last_line:c[c.length-1].last_line,first_column:c[c.length-(v||1)].first_column,last_column:c[c.length-1].last_column};E&&(F.ta.range=[c[c.length-(v||1)].range[0],c[c.length-1].range[1]]);k=this.performAction.apply(F,[n,y,l,u.yy,q[1],h,c].concat(z));if("undefined"!==typeof k)return k;v&&(e=e.slice(0,-2*v),h=h.slice(0,-1*v),c=c.slice(0,-1*v));e.push(this.Da[q[1]][0]);
h.push(F.c);c.push(F.ta);P=p[e[e.length-2]][e[e.length-1]];e.push(P);break;case 3:return!0}}}},Vb=function(){return{EOF:1,parseError:function(a,f){if(this.yy.parser)this.yy.parser.parseError(a,f);else throw Error(a);},setInput:function(a,f){this.yy=f||this.yy||{};this._input=a;this._more=this._backtrack=this.done=!1;this.yylineno=this.yyleng=0;this.yytext=this.matched=this.match="";this.conditionStack=["INITIAL"];this.yylloc={first_line:1,first_column:0,last_line:1,last_column:0};this.options.ranges&&
(this.yylloc.range=[0,0]);this.offset=0;return this},input:function(){var a=this._input[0];this.yytext+=a;this.yyleng++;this.offset++;this.match+=a;this.matched+=a;var f=a.match(/(?:\r\n?|\n).*/g);f?(this.yylineno++,this.yylloc.last_line++):this.yylloc.last_column++;this.options.ranges&&this.yylloc.range[1]++;this._input=this._input.slice(1);return a},unput:function(a){var f=a.length,b=a.split(/(?:\r\n?|\n)/g);this._input=a+this._input;this.yytext=this.yytext.substr(0,this.yytext.length-f);this.offset-=
f;var e=this.match.split(/(?:\r\n?|\n)/g);this.match=this.match.substr(0,this.match.length-1);this.matched=this.matched.substr(0,this.matched.length-1);b.length-1&&(this.yylineno-=b.length-1);a=this.yylloc.range;this.yylloc={first_line:this.yylloc.first_line,last_line:this.yylineno+1,first_column:this.yylloc.first_column,last_column:b?(b.length===e.length?this.yylloc.first_column:0)+e[e.length-b.length].length-b[0].length:this.yylloc.first_column-f};this.options.ranges&&(this.yylloc.range=[a[0],a[0]+
this.yyleng-f]);this.yyleng=this.yytext.length;return this},more:function(){this._more=!0;return this},reject:function(){if(this.options.backtrack_lexer)this._backtrack=!0;else return this.parseError("Lexical error on line "+(this.yylineno+1)+". You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n"+this.showPosition(),{text:"",token:null,line:this.yylineno});return this},less:function(a){this.unput(this.match.slice(a))},pastInput:function(){var a=
this.matched.substr(0,this.matched.length-this.match.length);return(20<a.length?"...":"")+a.substr(-20).replace(/\n/g,"")},upcomingInput:function(){var a=this.match;20>a.length&&(a+=this._input.substr(0,20-a.length));return(a.substr(0,20)+(20<a.length?"...":"")).replace(/\n/g,"")},showPosition:function(){var a=this.pastInput(),f=Array(a.length+1).join("-");return a+this.upcomingInput()+"\n"+f+"^"},test_match:function(a,f){var b,e;this.options.backtrack_lexer&&(e={yylineno:this.yylineno,yylloc:{first_line:this.yylloc.first_line,
last_line:this.last_line,first_column:this.yylloc.first_column,last_column:this.yylloc.last_column},yytext:this.yytext,match:this.match,matches:this.matches,matched:this.matched,yyleng:this.yyleng,offset:this.offset,_more:this._more,_input:this._input,yy:this.yy,conditionStack:this.conditionStack.slice(0),done:this.done},this.options.ranges&&(e.yylloc.range=this.yylloc.range.slice(0)));if(b=a[0].match(/(?:\r\n?|\n).*/g))this.yylineno+=b.length;this.yylloc={first_line:this.yylloc.last_line,last_line:this.yylineno+
1,first_column:this.yylloc.last_column,last_column:b?b[b.length-1].length-b[b.length-1].match(/\r?\n?/)[0].length:this.yylloc.last_column+a[0].length};this.yytext+=a[0];this.match+=a[0];this.matches=a;this.yyleng=this.yytext.length;this.options.ranges&&(this.yylloc.range=[this.offset,this.offset+=this.yyleng]);this._backtrack=this._more=!1;this._input=this._input.slice(a[0].length);this.matched+=a[0];a=this.performAction.call(this,this.yy,this,f,this.conditionStack[this.conditionStack.length-1]);
this.done&&this._input&&(this.done=!1);if(a)return a;if(this._backtrack)for(var h in e)this[h]=e[h];return!1},next:function(){if(this.done)return this.EOF;this._input||(this.done=!0);var a,f,b;this._more||(this.match=this.yytext="");for(var e=this._currentRules(),h=0;h<e.length;h++)if((f=this._input.match(this.rules[e[h]]))&&(!a||f[0].length>a[0].length))if(a=f,b=h,this.options.backtrack_lexer){a=this.test_match(f,e[h]);if(!1!==a)return a;if(this._backtrack)a=!1;else return!1}else if(!this.options.flex)break;
return a?(a=this.test_match(a,e[b]),!1!==a?a:!1):""===this._input?this.EOF:this.parseError("Lexical error on line "+(this.yylineno+1)+". Unrecognized text.\n"+this.showPosition(),{text:"",token:null,line:this.yylineno})},lex:function(){var a=this.next();return a?a:this.lex()},begin:function(a){this.conditionStack.push(a)},popState:function lc(){return 0<this.conditionStack.length-1?this.conditionStack.pop():this.conditionStack[0]},_currentRules:function mc(){return this.conditionStack.length&&this.conditionStack[this.conditionStack.length-
1]?this.conditions[this.conditionStack[this.conditionStack.length-1]].rules:this.conditions.INITIAL.rules},topState:function nc(a){a=this.conditionStack.length-1-Math.abs(a||0);return 0<=a?this.conditionStack[a]:"INITIAL"},pushState:function oc(a){this.begin(a)},stateStackSize:function pc(){return this.conditionStack.length},options:{},performAction:function(a,f,b,e){var h=e;switch(b){case 1:return 18;case 2:return 19;case 3:return 20;case 4:return 21;case 5:return 22;case 6:return 23;case 7:return 24;
case 8:return 25;case 9:return 26;case 10:return 27;case 11:return 28;case 12:return 29;case 13:return 30;case 14:return 31;case 15:return 32;case 16:return 33;case 17:return 34;case 18:return 35;case 19:return 11;case 20:return 10;case 21:return 16;case 22:return 48;case 23:return 62;case 24:return 60;case 25:return 49;case 26:return 50;case 27:return 51;case 28:return 52;case 29:return 53;case 30:return 58;case 31:return 59;case 32:return 54;case 33:return 55;case 34:return 56;case 35:return 57;
case 36:return 44;case 37:return 17;case 38:return 61;case 39:return 9;case 40:return 67;case 41:return 68;case 42:return 65;case 43:return 66;case 44:return 64;case 45:return 45;case 46:return 47;case 47:return"INVALID";case 48:return 5}},rules:[/^(?:\s+)/,/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)([Pp])([Xx]))/,/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)([Ee])([Mm]))/,/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)([Rr])([Ee])([Mm]))/,
/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)([Vv])([Hh]))/,/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)([Vv])([Ww]))/,/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)([Vv])([Mm])([Ii])([Nn]))/,/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)([Vv])([Mm])([Aa])([Xx]))/,/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)([Cc])([Mm]))/,
/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)([Mm])([Mm]))/,/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)([Qq]))/,/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)([Ii])([Nn]))/,/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)([Pp])([Cc]))/,/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)([Pp])([Tt]))/,/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)([Dd])([Ee])([Gg]))/,
/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)([Rr])([Aa])([Dd]))/,/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)([Gg])([Rr])([Aa])([Dd]))/,/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)([Mm])([Ss]))/,/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)([Ss]))/,/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)%)/,/^(?:([+-]?[0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?|[+-]?\.[0-9]+([eE][+\-]?[0-9]+)?)\b)/,
/^(?:#([a-fA-F0-9]+))/,/^(?:([Uu])([Rr])([Ll])\()/,/^(?:([Cc])([Aa])([Ll])([Cc])\()/,/^(?:([Vv])([Aa])([Rr])\()/,/^(?:([Tt])([Rr])([Aa])([Nn])([Ss])([Ll])([Aa])([Tt])([Ee])\()/,/^(?:([Tt])([Rr])([Aa])([Nn])([Ss])([Ll])([Aa])([Tt])([Ee])([Xx])\()/,/^(?:([Tt])([Rr])([Aa])([Nn])([Ss])([Ll])([Aa])([Tt])([Ee])([Yy])\()/,/^(?:([Tt])([Rr])([Aa])([Nn])([Ss])([Ll])([Aa])([Tt])([Ee])([Zz])\()/,/^(?:([Tt])([Rr])([Aa])([Nn])([Ss])([Ll])([Aa])([Tt])([Ee])3([Dd])\()/,/^(?:([Rr])([Aa])([Nn])([Dd])\()/,/^(?:([Ii])([Nn])([Dd])([Ee])([Xx])\()/,
/^(?:([Ww])([Ii])([Dd])([Tt])([Hh])\()/,/^(?:([Hh])([Ee])([Ii])([Gg])([Hh])([Tt])\()/,/^(?:([Cc])([Ll])([Oo])([Ss])([Ee])([Ss])([Tt])\()/,/^(?:([Nn])([Uu])([Mm])\()/,/^(?:(-?[a-zA-Z_][\-a-zA-Z0-9_]*)\()/,/^(?:(-?[a-zA-Z_][\-a-zA-Z0-9_]*))/,/^(?:--(-?[a-zA-Z_][\-a-zA-Z0-9_]*))/,/^(?:('[^\']*'|"[^\"]*"))/,/^(?:\+)/,/^(?:-)/,/^(?:\*)/,/^(?:\/)/,/^(?:\()/,/^(?:\))/,/^(?:,)/,/^(?:.)/,/^(?:$)/],conditions:{INITIAL:{rules:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,
31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48],inclusive:!0}}}}();Qa.lexer=Vb;b.prototype=Qa;Qa.Parser=b;return new b}();var yb={NORMAL:"normal",REVERSE:"reverse",ALTERNATE:"alternate",ALTERNATE_REVERSE:"alternate-reverse"},zb={NONE:"none",FORWARDS:"forwards",BACKWARDS:"backwards",BOTH:"both",AUTO:"auto"},Ab={opacity:!0,transform:!0,"transform-origin":!0,visibility:!0,"offset-distance":!0,offsetDistance:!0};var Bb=0,Cb={offset:!0,easing:!0};function Db(a){this.R=a;this.B=null;this.Y=0;this.X="idle";this.Ca=new Pa}t=Db.prototype;t.getPlayState=function(){return this.X};t.onPlayStateChanged=function(a){return this.Ca.add(a)};t.init=function(){var a=this;this.B=this.R.map(function(a){a.vars&&Ka(a.target,a.vars);var b=a.target.animate(a.keyframes,a.timing);b.pause();return b});this.Y=this.B.length;this.B.forEach(function(b){b.onfinish=function(){a.Y--;0==a.Y&&Eb(a,"finished")}})};
t.start=function(){this.B||this.init();this.resume()};t.pause=function(){Eb(this,"paused");this.B.forEach(function(a){"running"==a.playState&&a.pause()})};t.resume=function(){var a=this,b=this.X;"running"!=b&&(Eb(this,"running"),this.Y=0,this.B.forEach(function(c){if("paused"!=b||"paused"==c.playState)c.play(),a.Y++}))};t.reverse=function(){this.B.forEach(function(a){a.reverse()})};t.seekTo=function(a){Eb(this,"paused");this.B.forEach(function(b){b.pause();b.currentTime=a})};
t.seekToPercent=function(a){for(var b=0,c=0;c<this.R.length;c++){var d=this.R[c].timing;I().assert(isFinite(d.iterations),'Animation has infinite timeline, we can not seek to a relative position within an infinite timeline. Use "time" for seekTo or remove infinite iterations');d=d.duration*(d.iterations-d.iterationStart)+d.delay+d.endDelay;d>b&&(b=d)}var k=b;this.seekTo(k*a)};t.finish=function(){if(this.B){var a=this.B;this.B=null;Eb(this,"finished");a.forEach(function(a){a.finish()})}};
t.cancel=function(){this.B&&(Eb(this,"idle"),this.B.forEach(function(a){a.cancel()}))};function Eb(a,b){a.X!=b&&(a.X=b,a.Ca.fire(a.X))}function Fb(){}t=Fb.prototype;
t.scan=function(a){var b=this;if(Array.isArray(a))return a.reduce(function(a,d){return b.scan(d)||a},!1);if(!this.isEnabled(a))return!1;if(a.animations)this.onMultiAnimation(a);else if(a.switch)this.onSwitchAnimation(a);else if(a.animation)this.onCompAnimation(a);else if(a.keyframes)this.onKeyframeAnimation(a);else this.onUnknownAnimation(a);return!0};t.isEnabled=function(){return!0};t.onMultiAnimation=function(){};t.onSwitchAnimation=function(){};t.onCompAnimation=function(){};
t.onKeyframeAnimation=function(){};t.onUnknownAnimation=function(){throw ha().createError('unknown animation type: must have "animations" or "keyframes" field');};function Gb(a,b,c,d,k){this.h=new Hb(a,b,c);this.sa=d;this.ma=k;this.Ga=[];this.ya=[]}Gb.prototype.createRunner=function(a,b){var c=this;return this.resolveRequests([],a,b).then(function(a){ea();return Promise.all(c.ya).then(function(){return new Db(a)})})};
Gb.prototype.resolveRequests=function(a,b,c,d,k,m,q){m=void 0===m?null:m;var w=new Ib(this,this.h,a,void 0===d?null:d,void 0===k?null:k,m,void 0===q?null:q);return this.sa.measurePromise(function(){return w.resolveRequests(b,c)})};Gb.prototype.requireLayout=function(a){this.Ga.includes(a)||(this.Ga.push(a),this.ya.push(this.ma.requireLayout(a)))};
function Ib(a,b,c,d,k,m,q){this.ua=a;this.h=b;this.Ba=c;this.G=d;this.U=k;this.w=m||ia();this.ba=q||{duration:0,delay:0,endDelay:0,iterations:1,iterationStart:0,easing:"linear",direction:"normal",fill:"none"};this.R=[];this.wa=[]}C(Ib,Fb);t=Ib.prototype;t.resolveRequests=function(a,b){var c=this;b?Jb(this,b,function(){c.scan(a)}):this.h.withVars(this.w,function(){c.scan(a)});return Promise.all(this.wa).then(function(){return c.R})};
t.isEnabled=function(a){return a.media&&!this.h.matchMedia(a.media)||a.supports&&!this.h.supports(a.supports)?!1:!0};t.onMultiAnimation=function(a){var b=this;Jb(this,a,function(){return b.scan(a.animations)})};t.onSwitchAnimation=function(a){var b=this;Jb(this,a,function(){for(var c=0;c<a.switch.length&&!b.scan(a.switch[c]);c++);})};
t.onCompAnimation=function(a){var b=this;I().assert(-1==this.Ba.indexOf(a.animation),'Recursive animations are not allowed: "'+a.animation+'"');var c=this.Ba.concat(a.animation),d=I().assertElement(this.h.getElementById(a.animation),'Animation not found: "'+a.animation+'"');I().assert("AMP-ANIMATION"==d.tagName,'Element is not an animation: "'+a.animation+'"');var k=d.getImpl().then(function(a){return a.getAnimationSpec()});Jb(this,a,function(){var a=b.G,d=b.U,w=b.w,g=b.ba,u=k.then(function(u){if(u)return b.ua.resolveRequests(c,
u,null,a,d,w,g)}).then(function(a){a.forEach(function(a){return b.R.push(a)})});b.wa.push(u)})};t.onKeyframeAnimation=function(a){var b=this;Jb(this,a,function(){var c=I().assertElement(b.G,"No target specified"),d=Kb(b,c,a);b.R.push({target:c,keyframes:d,vars:b.w,timing:b.ba})})};
function Kb(a,b,c){var d=c.keyframes;"string"==typeof d&&(c=ub(a.h.ia,d),I().assert(c,'Keyframes not found in stylesheet: "'+d+'"'),d=c);if("[object Object]"===fa.call(d)){var k=d;c={};for(var m in k){Lb(m);var q=k[m],w=void 0;if(Cb[m])w=q;else if(Array.isArray(q)&&1!=q.length)w=q.map(function(b){return a.h.resolveCss(b)});else var g=a.h.measure(b,m),u=Array.isArray(q)?q[0]:q,w=[g,a.h.resolveCss(u)];c[m]=w}return c}if(Array.isArray(d)&&0<d.length){m=d;c=[];var A=1==m.length||0<m[0].offset,n=A?ia():
a.h.resolveCssMap(m[0]);c.push(n);for(q=A?0:1;q<m.length;q++){var l=m[q];for(k in l)Cb[k]||(Lb(k),n[k]||(n[k]=a.h.measure(b,k)));c.push(a.h.resolveCssMap(l))}return c}throw I().createError("keyframes not found",d);}t.onUnknownAnimation=function(){throw I().createError('unknown animation type: must have "animation", "animations" or "keyframes" field');};function Lb(a){Cb[a]||I().assert(Ab[a]||!1,"Property is not whitelisted for animation: %s",a)}
function Jb(a,b,c){var d=a.G,k=a.U,m=a.w,q=a.ba,w=b.target||b.selector?Mb(a,b):[null];w.forEach(function(g,u){a.G=g||d;a.U=g?u:k;a.h.withTarget(a.G,a.U,function(){var g=a.G?Nb(a.G,a.U||0,b):b;a.w=Ob(a,g,m);a.h.withVars(a.w,function(){var b=g,l=q,d=a.h.resolveMillis(b.duration,l.duration),e=a.h.resolveMillis(b.delay,l.delay),f=a.h.resolveMillis(b.endDelay,l.endDelay),h=a.h.resolveNumber(b.iterations,l.iterations),z=a.h.resolveNumber(b.iterationStart,l.iterationStart),y=a.h.resolveIdent(b.easing,l.easing),
p=a.h.resolveIdent(b.direction,l.direction),l=a.h.resolveIdent(b.fill,l.fill);Pb(d,b.duration,"duration");Pb(e,b.delay,"delay",!0);Pb(f,b.endDelay,"endDelay");I().assert(null!=h&&0<=h,'"iterations" is invalid: %s',b.iterations);I().assert(null!=z&&0<=z&&isFinite(z),'"iterationStart" is invalid: %s',b.iterationStart);I().assertEnumValue(yb,p,"direction");I().assertEnumValue(zb,l,"fill");a.ba={duration:d,delay:e,endDelay:f,iterations:h,iterationStart:z,easing:y,direction:p,fill:l};c()})})});a.G=d;a.U=
k;a.w=m;a.ba=q}
function Mb(a,b){var c;b.selector?(I().assert(!b.target,'Both "selector" and "target" are not allowed'),c=a.h.queryElements(b.selector),0==c.length&&I().warn("amp-animation",'Target not found: "'+b.selector+'"')):b.target?("string"==typeof b.target&&I().error("amp-animation","string targets are deprecated"),c=[I().assertElement("string"==typeof b.target?a.h.getElementById(b.target):b.target,'Target not found: "'+b.target+'"')]):a.G&&(c=[a.G]);c.forEach(function(b){return a.ua.requireLayout(b)});return c}
function Nb(a,b,c){if(!c.subtargets||0==c.subtargets.length)return c;var d=ia(c);c.subtargets.forEach(function(c){Qb(c)(a,b)&&Object.assign(d,c)});return d}
function Qb(a){if(a.matcher)return a.matcher;I().assert((void 0!==a.index||void 0!==a.selector)&&(void 0===a.index||void 0===a.selector),'Only one "index" or "selector" must be specified');var b;if(void 0!==a.index){var c=Number(a.index);b=function(a,b){return b===c}}else{var d=a.selector;b=function(a){try{return Ba(a,d)}catch(m){throw I().createError('Bad subtarget selector: "'+d+'"',m);}}}return a.matcher=b}
function Ob(a,b,c){var d=ia(c),k;for(k in b)oa(k,"--")&&(d[k]=b[k]);a.h.withVars(d,function(){for(var c in b)oa(c,"--")&&(d[c]=a.h.resolveCss(b[c]))});return d}function Pb(a,b,c,d){I().assert(null!=a&&(0<=a||0>a&&d),'"%s" is invalid: %s',c,b);null!=b&&Math.floor(a)!=a&&1>a&&I().warn("amp-animation",'"'+c+'" is fractional. Note that all times are in milliseconds.')}function Hb(a,b,c){this.O=a;this.ia=b;this.Ja=c;this.va=ia();this.Aa=ia();this.w=this.ga=this.P=null;this.qa=[];this.ra=this.S=null}
t=Hb.prototype;t.matchMedia=function(a){return this.O.matchMedia(a).matches};t.supports=function(a){return this.O.CSS&&this.O.CSS.supports?this.O.CSS.supports(a):!1};t.getElementById=function(a){return this.ia.getElementById(a)};t.queryElements=function(a){try{var b;var c=this.ia.querySelectorAll(a);if(c){for(var d=Array(c.length),k=0;k<c.length;k++)d[k]=c[k];b=d}else b=[];return b}catch(m){throw I().createError('Bad query selector: "'+a+'"',m);}};
t.measure=function(a,b){var c=a.__AMP_ANIM_ID;c||(c=String(++Bb),a.__AMP_ANIM_ID=c);var d=this.va[c];d||(d=this.O.getComputedStyle(a)||ia(),this.va[c]=d);return oa(b,"--")?d.getPropertyValue(b):d[Ja(d,b.replace(/-([a-z])/g,ka))]};t.withTarget=function(a,b,c){var d=this.P,k=this.ga;this.P=a;this.ga=b;a=c(a);this.P=d;this.ga=k;return a};t.withVars=function(a,b){var c=this.w;this.w=a;a=b();this.w=c;return a};t.resolveCss=function(a){return Rb(this,a,"",!0)};
t.resolveCssMap=function(a){var b=ia(),c;for(c in a)b[c]="offset"==c?a[c]:this.resolveCss(a[c]);return b};t.resolveIdent=function(a,b){return Rb(this,a,b,!1)};t.resolveMillis=function(a,b){if(null!=a&&""!==a){if("number"==typeof a)return a;if(a=Sb(this,a,!1))b=a instanceof db?eb(a):a instanceof X?a.l:void 0}return b};t.resolveNumber=function(a,b){if(null!=a&&""!==a){if("number"==typeof a)return a;if(a=Sb(this,a,!1))a instanceof X?b=a.l:(b=a.css(),b=Xa.test(b)?Infinity:void 0)}return b};
function Rb(a,b,c,d){if(null==b||""===b)return c;var k=String(b);(b="number"==typeof b)||(b=k,b=!(Va.test(b)||d&&Wa.test(b)));if(b)return k;a=Sb(a,k,d);return null!=a?a.css():c}function Sb(a,b,c){if(null==b||""===b)return null;if("number"==typeof b)return new X(b);b=String(b);var d=a.Aa[b];void 0===d&&(d=xb.parse(b),a.Aa[b]=d);return d?d.resolve(a,c):null}function Tb(a){return I().assertElement(a.P,"Only allowed when target is specified")}
t.getVar=function(a){I().assert(-1==this.qa.indexOf(a),'Recursive variable: "'+a+'"');this.qa.push(a);var b=this.w&&void 0!=this.w[a]?this.w[a]:this.P?this.measure(this.P,a):null;null!=b&&""!==b||I().warn("amp-animation",'Variable not found: "'+a+'"');a=Sb(this,b,!1);this.qa.pop();return a};t.withDimension=function(a,b){var c=this.S;this.S=a;a=b();this.S=c;return a};t.getDimension=function(){return this.S};
t.getViewportSize=function(){this.ra||(this.ra={width:this.O.innerWidth,height:this.O.innerHeight});return this.ra};t.getCurrentIndex=function(){Tb(this);return this.ga};t.getCurrentFontSize=function(){var a=Tb(this);return parseFloat(this.measure(a,"font-size"))};t.getRootFontSize=function(){return parseFloat(this.measure(this.O.document.documentElement,"font-size"))};t.getCurrentElementSize=function(){return Ub(Tb(this))};
t.getElementSize=function(a,b){var c;try{c="closest"==b?Aa(Tb(this),a):this.ia.querySelector(a)}catch(d){throw I().createError('Bad query selector: "'+a+'"',d);}a=I().assertElement(c,"Element not found: "+a);return Ub(a)};function Ub(a){a=a.getBoundingClientRect();return{width:a.width,height:a.height}}
t.resolveUrl=function(a){var b=this.Ja;"string"==typeof b&&(b=ra(b));if("function"==typeof URL)a=(new URL(a,b.href)).toString();else{"string"==typeof b&&(b=ra(b));a=a.replace(/\\/g,"/");var c=ra(a);a=oa(a.toLowerCase(),c.protocol)?c.href:oa(a,"//")?b.protocol+a:oa(a,"/")?b.origin+a:b.origin+b.pathname.replace(/\/[^/]*$/,"/")+a}var d=a;a=d;var b=this.P||"",k;k=void 0===k?"source":k;I().assert(null!=a,"%s %s must be available",b,k);I().assert(sa(a)||/^(\/\/)/.test(a),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',
b,k,a);return a};function Wb(a,b,c){var d=this;this.Ha=ua(a,"timer");this.Pa=b;this.Na=c||0;this.Z=-1;this.la=0;this.na=!1;this.Ka=function(){d.Z=-1;d.la=0;d.na=!0;d.Pa();d.na=!1}}Wb.prototype.isPending=function(){return-1!=this.Z};Wb.prototype.schedule=function(a){a=a||this.Na;this.na&&10>a&&(a=10);var b=Date.now()+a;return!this.isPending()||-10>b-this.la?(this.cancel(),this.la=b,this.Z=this.Ha.delay(this.Ka,a),!0):!1};Wb.prototype.cancel=function(){this.isPending()&&(this.Ha.cancel(this.Z),this.Z=-1)};function Xb(a){var b=a.document;!function(c,d){var k={},m={};!function(a){function c(a){return a}function g(){this._endDelay=this._delay=0;this._fill="none";this._iterationStart=0;this._iterations=1;this._duration=0;this._playbackRate=1;this._direction="normal";this._easing="linear";this._easingFunction=c}function d(){return a.isDeprecated("Invalid timing inputs","2016-03-02","TypeError exceptions will be thrown instead.",!0)}function k(b,f){var e=new g;return f&&(e.fill="both",e.duration="auto"),
"number"!=typeof b||isNaN(b)?void 0!==b&&Object.getOwnPropertyNames(b).forEach(function(f){"auto"==b[f]||("number"==typeof e[f]||"duration"==f)&&("number"!=typeof b[f]||isNaN(b[f]))||"fill"==f&&-1==E.indexOf(b[f])||"direction"==f&&-1==D.indexOf(b[f])||"playbackRate"==f&&1!==b[f]&&a.isDeprecated("AnimationEffectTiming.playbackRate","2014-11-28","Use Animation.playbackRate instead.")||(e[f]=b[f])}):e.duration=b,e}function n(a){return"number"==typeof a&&(a=isNaN(a)?{duration:0}:{duration:a}),a}function l(a,
f,b,e){return 0>a||1<a||0>b||1<b?c:function(h){if(0>=h){var c=0;return 0<a?c=f/a:!f&&0<b&&(c=e/b),c*h}if(1<=h)return c=0,1>b?c=(e-1)/(b-1):1==b&&1>a&&(c=(f-1)/(a-1)),1+c*(h-1);for(var c=0,g=1;c<g;){var p=(c+g)/2,l=3*a*(1-p)*(1-p)*p+3*b*(1-p)*p*p+p*p*p;if(1E-5>Math.abs(h-l))break;l<h?c=p:g=p}return 3*f*(1-p)*(1-p)*p+3*e*(1-p)*p*p+p*p*p}}function r(a,b){return function(f){if(1<=f)return 1;var e=1/a;return(f+=b*e)-f%e}}function e(a){H||(H=b.createElement("div").style);H.animationTimingFunction="";H.animationTimingFunction=
a;var f=H.animationTimingFunction;if(""==f&&d())throw new TypeError(a+" is not a valid value for easing");return f}function f(a){if("linear"==a)return c;var f=S.exec(a);return f?l.apply(this,f.slice(1).map(Number)):(f=T.exec(a))?r(Number(f[1]),{start:G,middle:B,end:m}[f[2]]):q[a]||c}function h(a){return Math.abs((0===a.duration||0===a.iterations?0:a.duration*a.iterations)/a.playbackRate)}function z(a,f,b){if(null==f)return N;var e=b.delay+a+b.endDelay;return f<Math.min(b.delay,e)?M:f>=Math.min(b.delay+
a,e)?K:O}function y(a,f,b,e,h){return 0===a?f!==M&&(h+=b):h+=e/a,h}function p(a,f,b){var e=a;"normal"!==a&&"reverse"!==a&&("alternate-reverse"===a&&(f+=1),e="normal",f!==1/0&&0!=f%2&&(e="reverse"));return"normal"===e?b:1-b}function x(a,f,b){var e=z(a,f,b),h;a:{h=b.fill;switch(e){case M:h="backwards"==h||"both"==h?0:null;break a;case O:h=f-b.delay;break a;case K:h="forwards"==h||"both"==h?a:null;break a;case N:h=null;break a}h=void 0}if(null===h)return null;a=y(b.duration,e,b.iterations,h,b.iterationStart);
f=a===1/0?b.iterationStart%1:a%1;h=(0!==f||e!==K||0===b.iterations||0===h&&0!==b.duration||(f=1),f);e=p(b.direction,e===K&&b.iterations===1/0?1/0:1===h?Math.floor(a)-1:Math.floor(a),h);return b._easingFunction(e)}var E=["backwards","forwards","both","none"],D=["reverse","alternate","alternate-reverse"];g.prototype={_setMember:function(f,b){this["_"+f]=b;this._effect&&(this._effect._timingInput[f]=b,this._effect._timing=a.normalizeTimingInput(this._effect._timingInput),this._effect.activeDuration=
a.calculateActiveDuration(this._effect._timing),this._effect._animation&&this._effect._animation._rebuildUnderlyingAnimation())},get playbackRate(){return this._playbackRate},set delay(a){this._setMember("delay",a)},get delay(){return this._delay},set endDelay(a){this._setMember("endDelay",a)},get endDelay(){return this._endDelay},set fill(a){this._setMember("fill",a)},get fill(){return this._fill},set iterationStart(a){if((isNaN(a)||0>a)&&d())throw new TypeError("iterationStart must be a non-negative number, received: "+
timing.iterationStart);this._setMember("iterationStart",a)},get iterationStart(){return this._iterationStart},set duration(a){if("auto"!=a&&(isNaN(a)||0>a)&&d())throw new TypeError("duration must be non-negative or auto, received: "+a);this._setMember("duration",a)},get duration(){return this._duration},set direction(a){this._setMember("direction",a)},get direction(){return this._direction},set easing(a){this._easingFunction=f(e(a));this._setMember("easing",a)},get easing(){return this._easing},set iterations(a){if((isNaN(a)||
0>a)&&d())throw new TypeError("iterations must be non-negative, received: "+a);this._setMember("iterations",a)},get iterations(){return this._iterations}};var G=1,B=.5,m=0,q={ease:l(.25,.1,.25,1),"ease-in":l(.42,0,1,1),"ease-out":l(0,0,.58,1),"ease-in-out":l(.42,0,.58,1),"step-start":r(1,G),"step-middle":r(1,B),"step-end":r(1,m)},H=null,J="\\s*(-?\\d+\\.?\\d*|-?\\.\\d+)\\s*",S=new RegExp("cubic-bezier\\("+J+","+J+","+J+","+J+"\\)"),T=/steps\(\s*(\d+)\s*,\s*(start|middle|end)\s*\)/,N=0,M=1,K=2,O=3;
a.cloneTimingInput=function(a){if("number"==typeof a)return a;var f={},b;for(b in a)f[b]=a[b];return f};a.makeTiming=k;a.numericTimingToObject=n;a.normalizeTimingInput=function(f,b){return f=a.numericTimingToObject(f),k(f,b)};a.calculateActiveDuration=h;a.calculateIterationProgress=x;a.calculatePhase=z;a.normalizeEasing=e;a.parseEasingFunction=f}(k);(function(c){function d(a){var b=[],e;for(e in a)if(!(e in["easing","offset","composite"])){var f=a[e];Array.isArray(f)||(f=[f]);for(var h,c=f.length,
g=0;g<c;g++)h={},h.offset="offset"in a?a.offset:1==c?1:g/(c-1),"easing"in a&&(h.easing=a.easing),"composite"in a&&(h.composite=a.composite),h[e]=f[g],b.push(h)}return b.sort(function(a,b){return a.offset-b.offset}),b}var g={background:"backgroundImage backgroundPosition backgroundSize backgroundRepeat backgroundAttachment backgroundOrigin backgroundClip backgroundColor".split(" "),border:"borderTopColor borderTopStyle borderTopWidth borderRightColor borderRightStyle borderRightWidth borderBottomColor borderBottomStyle borderBottomWidth borderLeftColor borderLeftStyle borderLeftWidth".split(" "),
borderBottom:["borderBottomWidth","borderBottomStyle","borderBottomColor"],borderColor:["borderTopColor","borderRightColor","borderBottomColor","borderLeftColor"],borderLeft:["borderLeftWidth","borderLeftStyle","borderLeftColor"],borderRadius:["borderTopLeftRadius","borderTopRightRadius","borderBottomRightRadius","borderBottomLeftRadius"],borderRight:["borderRightWidth","borderRightStyle","borderRightColor"],borderTop:["borderTopWidth","borderTopStyle","borderTopColor"],borderWidth:["borderTopWidth",
"borderRightWidth","borderBottomWidth","borderLeftWidth"],flex:["flexGrow","flexShrink","flexBasis"],font:"fontFamily fontSize fontStyle fontVariant fontWeight lineHeight".split(" "),margin:["marginTop","marginRight","marginBottom","marginLeft"],outline:["outlineColor","outlineStyle","outlineWidth"],padding:["paddingTop","paddingRight","paddingBottom","paddingLeft"]},u=b.createElementNS("http://www.w3.org/1999/xhtml","div"),k={thin:"1px",medium:"3px",thick:"5px"},n={borderBottomWidth:k,borderLeftWidth:k,
borderRightWidth:k,borderTopWidth:k,fontSize:{"xx-small":"60%","x-small":"75%",small:"89%",medium:"100%",large:"120%","x-large":"150%","xx-large":"200%"},fontWeight:{normal:"400",bold:"700"},outlineWidth:k,textShadow:{none:"0px 0px 0px transparent"},boxShadow:{none:"0px 0px 0px 0px transparent"}};c.convertToArrayForm=d;c.normalizeKeyframes=function(b){function l(){var a=e.length;null==e[a-1].offset&&(e[a-1].offset=1);1<a&&null==e[0].offset&&(e[0].offset=0);for(var b=0,f=e[0].offset,h=1;h<a;h++){var c=
e[h].offset;if(null!=c){for(var g=1;g<h-b;g++)e[b+g].offset=f+(c-f)*g/(h-b);b=h;f=c}}}if(null==b)return[];a.Symbol&&Symbol.iterator&&Array.prototype.from&&b[Symbol.iterator]&&(b=Array.from(b));Array.isArray(b)||(b=d(b));var e=b.map(function(a){var b={},f;for(f in a){var e=a[f];if("offset"==f){if(null!=e){if(e=Number(e),!isFinite(e))throw new TypeError("Keyframe offsets must be numbers.");if(0>e||1<e)throw new TypeError("Keyframe offsets must be between 0 and 1.");}}else if("composite"==f){if("add"==
e||"accumulate"==e)throw{type:DOMException.NOT_SUPPORTED_ERR,name:"NotSupportedError",message:"add compositing is not supported"};if("replace"!=e)throw new TypeError("Invalid composite mode "+e+".");}else e="easing"==f?c.normalizeEasing(e):""+e;var h=void 0,d=f,l=e,e=b,r=d;if("display"!==r&&0!==r.lastIndexOf("animation",0)&&0!==r.lastIndexOf("transition",0))if(r=g[d])for(h in u.style[d]=l,r)d=r[h],l=u.style[d],e[d]=d in n?n[d][l]||l:l;else e[d]=d in n?n[d][l]||l:l}return void 0==b.offset&&(b.offset=
null),void 0==b.easing&&(b.easing="linear"),b});b=!0;for(var f=-1/0,h=0;h<e.length;h++){var z=e[h].offset;if(null!=z){if(z<f)throw new TypeError("Keyframes are not loosely sorted by offset. Sort or specify offsets.");f=z}else b=!1}return e=e.filter(function(a){return 0<=a.offset&&1>=a.offset}),b||l(),e}})(k);(function(a){var b={};a.isDeprecated=function(a,c,d,n){n=n?"are":"is";var g=new Date;c=new Date(c);return c.setMonth(c.getMonth()+3),!(g<c&&(a in b||console.warn("Web Animations: "+a+" "+n+" deprecated and will stop working on "+
c.toDateString()+". "+d),b[a]=!0,1))};a.deprecated=function(b,c,d,n){var g=n?"are":"is";if(a.isDeprecated(b,c,d,n))throw Error(b+" "+g+" no longer supported. "+d);}})(k);(function(){if(b.documentElement.animate){var c=b.documentElement.animate([],0),d=!0;if(c&&(d=!1,"play currentTime pause reverse playbackRate cancel finish startTime playState".split(" ").forEach(function(a){void 0===c[a]&&(d=!0)})),!d)return}!function(a,b){function c(a){for(var b={},e=0;e<a.length;e++)for(var f in a[e])if("offset"!=
f&&"easing"!=f&&"composite"!=f){var h={offset:a[e].offset,easing:a[e].easing,value:a[e][f]};b[f]=b[f]||[];b[f].push(h)}for(var c in b)if(a=b[c],0!=a[0].offset||1!=a[a.length-1].offset)throw{type:DOMException.NOT_SUPPORTED_ERR,name:"NotSupportedError",message:"Partial keyframes are not supported"};return b}function g(c){var g=[],e;for(e in c)for(var f=c[e],h=0;h<f.length-1;h++){var d=h,n=h+1,p=f[d].offset,l=f[n].offset,k=p,u=l;0==h&&(k=-1/0,0==l&&(n=d));h==f.length-2&&(u=1/0,1==p&&(d=n));g.push({applyFrom:k,
applyTo:u,startOffset:f[d].offset,endOffset:f[n].offset,easingFunction:a.parseEasingFunction(f[d].easing),property:e,interpolation:b.propertyInterpolation(e,f[d].value,f[n].value)})}return g.sort(function(a,b){return a.startOffset-b.startOffset}),g}b.convertEffectInput=function(d){d=a.normalizeKeyframes(d);var n=c(d),e=g(n);return function(a,h){if(null!=h)e.filter(function(a){return h>=a.applyFrom&&h<a.applyTo}).forEach(function(f){var e=h-f.startOffset,c=f.endOffset-f.startOffset,e=0==c?0:f.easingFunction(e/
c);b.apply(a,f.property,f.interpolation(e))});else for(var f in n)"offset"!=f&&"easing"!=f&&"composite"!=f&&b.clear(a,f)}}}(k,m);(function(a,b){function c(a){return a.replace(/-(.)/g,function(a,b){return b.toUpperCase()})}var g={};b.addPropertiesHandler=function(a,b,f){for(var e=0;e<f.length;e++){var d=a,n=b,p=c(f[e]);g[p]=g[p]||[];g[p].push([d,n])}};var d={backgroundColor:"transparent",backgroundPosition:"0% 0%",borderBottomColor:"currentColor",borderBottomLeftRadius:"0px",borderBottomRightRadius:"0px",
borderBottomWidth:"3px",borderLeftColor:"currentColor",borderLeftWidth:"3px",borderRightColor:"currentColor",borderRightWidth:"3px",borderSpacing:"2px",borderTopColor:"currentColor",borderTopLeftRadius:"0px",borderTopRightRadius:"0px",borderTopWidth:"3px",bottom:"auto",clip:"rect(0px, 0px, 0px, 0px)",color:"black",fontSize:"100%",fontWeight:"400",height:"auto",left:"auto",letterSpacing:"normal",lineHeight:"120%",marginBottom:"0px",marginLeft:"0px",marginRight:"0px",marginTop:"0px",maxHeight:"none",
maxWidth:"none",minHeight:"0px",minWidth:"0px",opacity:"1.0",outlineColor:"invert",outlineOffset:"0px",outlineWidth:"3px",paddingBottom:"0px",paddingLeft:"0px",paddingRight:"0px",paddingTop:"0px",right:"auto",strokeDasharray:"none",strokeDashoffset:"0px",textIndent:"0px",textShadow:"0px 0px 0px transparent",top:"auto",transform:"",verticalAlign:"0px",visibility:"visible",width:"auto",wordSpacing:"normal",zIndex:"auto"};b.propertyInterpolation=function(n,e,f){var h=n;/-/.test(n)&&!a.isDeprecated("Hyphenated property names",
"2016-03-22","Use camelCase instead.",!0)&&(h=c(n));"initial"!=e&&"initial"!=f||("initial"==e&&(e=d[h]),"initial"==f&&(f=d[h]));n=e==f?[]:g[h];for(h=0;n&&h<n.length;h++){var l=n[h][0](e),r=n[h][0](f);if(void 0!==l&&void 0!==r&&(l=n[h][1](l,r))){var p=b.Interpolation.apply(null,l);return function(a){return 0==a?e:1==a?f:p(a)}}}return b.Interpolation(!1,!0,function(a){return a?f:e})}})(k,m);(function(a,b){function c(b){function c(e){return a.calculateIterationProgress(g,e,b)}var g=a.calculateActiveDuration(b);
return c._totalDuration=b.delay+g+b.endDelay,c}b.KeyframeEffect=function(g,d,r,e){function f(){l(g,h)}var h,n=c(a.normalizeTimingInput(r)),l=b.convertEffectInput(d);return f._update=function(a){return null!==(h=n(a))},f._clear=function(){l(g,null)},f._hasSameTarget=function(a){return g===a},f._target=g,f._totalDuration=n._totalDuration,f._id=e,f}})(k,m);(function(c){function g(a,b,f){f.enumerable=!0;f.configurable=!0;Object.defineProperty(a,b,f)}function d(f){this._element=f;this._surrogateStyle=
b.createElementNS("http://www.w3.org/1999/xhtml","div").style;this._style=f.style;this._length=0;this._isAnimatedProperty={};this._updateSvgTransformAttr=!(!f.namespaceURI||-1==f.namespaceURI.indexOf("/svg"))&&(l in a||(a[l]=/Trident|MSIE|IEMobile|Edge|Android 4/i.test(a.navigator.userAgent)),a[l]);this._savedTransformAttr=null;for(f=0;f<this._style.length;f++){var e=this._style[f];this._surrogateStyle[e]=this._style[e]}this._updateIndices()}function n(a){if(!a._webAnimationsPatchedStyle){var b=new d(a);
try{g(a,"style",{get:function(){return b}})}catch(x){a.style._set=function(b,f){a.style[b]=f},a.style._clear=function(b){a.style[b]=""}}a._webAnimationsPatchedStyle=a.style}}var l="_webAnimationsUpdateSvgTransformAttr",r={cssText:1,length:1,parentRule:1},e={getPropertyCSSValue:1,getPropertyPriority:1,getPropertyValue:1,item:1,removeProperty:1,setProperty:1},f={removeProperty:1,setProperty:1};d.prototype={get cssText(){return this._surrogateStyle.cssText},set cssText(a){for(var b={},f=0;f<this._surrogateStyle.length;f++)b[this._surrogateStyle[f]]=
!0;this._surrogateStyle.cssText=a;this._updateIndices();for(f=0;f<this._surrogateStyle.length;f++)b[this._surrogateStyle[f]]=!0;for(var e in b)this._isAnimatedProperty[e]||this._style.setProperty(e,this._surrogateStyle.getPropertyValue(e))},get length(){return this._surrogateStyle.length},get parentRule(){return this._style.parentRule},_updateIndices:function(){for(;this._length<this._surrogateStyle.length;)Object.defineProperty(this,this._length,{configurable:!0,enumerable:!1,get:function(a){return function(){return this._surrogateStyle[a]}}(this._length)}),
this._length++;for(;this._length>this._surrogateStyle.length;)this._length--,Object.defineProperty(this,this._length,{configurable:!0,enumerable:!1,value:void 0})},_set:function(a,b){this._style[a]=b;this._isAnimatedProperty[a]=!0;this._updateSvgTransformAttr&&"transform"==c.unprefixedPropertyName(a)&&(null==this._savedTransformAttr&&(this._savedTransformAttr=this._element.getAttribute("transform")),this._element.setAttribute("transform",c.transformToSvgMatrix(b)))},_clear:function(a){this._style[a]=
this._surrogateStyle[a];this._updateSvgTransformAttr&&"transform"==c.unprefixedPropertyName(a)&&(this._savedTransformAttr?this._element.setAttribute("transform",this._savedTransformAttr):this._element.removeAttribute("transform"),this._savedTransformAttr=null);delete this._isAnimatedProperty[a]}};for(var h in e)d.prototype[h]=function(a,b){return function(){var f=this._surrogateStyle[a].apply(this._surrogateStyle,arguments);return b&&(this._isAnimatedProperty[arguments[0]]||this._style[a].apply(this._style,
arguments),this._updateIndices()),f}}(h,h in f);for(var k in b.documentElement.style)k in r||k in e||function(a){g(d.prototype,a,{get:function(){return this._surrogateStyle[a]},set:function(b){this._surrogateStyle[a]=b;this._updateIndices();this._isAnimatedProperty[a]||(this._style[a]=b)}})}(k);c.apply=function(a,b,f){n(a);a.style._set(c.propertyName(b),f)};c.clear=function(a,b){a._webAnimationsPatchedStyle&&a.style._clear(c.propertyName(b))}})(m);(function(b){a.Element.prototype.animate=function(a,
c){var g="";return c&&c.id&&(g=c.id),b.timeline._play(b.KeyframeEffect(this,a,c,g))}})(m);(function(a){function b(a,c,g){if("number"==typeof a&&"number"==typeof c)return a*(1-g)+c*g;if("boolean"==typeof a&&"boolean"==typeof c)return.5>g?a:c;if(a.length==c.length){for(var d=[],e=0;e<a.length;e++)d.push(b(a[e],c[e],g));return d}throw"Mismatched interpolation arguments "+a+":"+c;}a.Interpolation=function(a,c,g){return function(d){return g(b(a,c,d))}}})(m);(function(a){var b=function(){function a(a,b){for(var c=
[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]],e=0;4>e;e++)for(var f=0;4>f;f++)for(var h=0;4>h;h++)c[e][f]+=b[e][h]*a[h][f];return c}return function(b,c,g,e,f){for(var h=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],d=0;4>d;d++)h[d][3]=f[d];for(d=0;3>d;d++)for(f=0;3>f;f++)h[3][d]+=b[f]*h[f][d];b=e[0];d=e[1];f=e[2];e=e[3];var n=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]];n[0][0]=1-2*(d*d+f*f);n[0][1]=2*(b*d-f*e);n[0][2]=2*(b*f+d*e);n[1][0]=2*(b*d+f*e);n[1][1]=1-2*(b*b+f*f);n[1][2]=2*(d*f-b*e);n[2][0]=2*(b*f-
d*e);n[2][1]=2*(d*f+b*e);n[2][2]=1-2*(b*b+d*d);h=a(h,n);e=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]];g[2]&&(e[2][1]=g[2],h=a(h,e));g[1]&&(e[2][1]=0,e[2][0]=g[0],h=a(h,e));g[0]&&(e[2][0]=0,e[1][0]=g[0],h=a(h,e));for(d=0;3>d;d++)for(f=0;3>f;f++)h[d][f]*=c[d];return 0==h[0][2]&&0==h[0][3]&&0==h[1][2]&&0==h[1][3]&&0==h[2][0]&&0==h[2][1]&&1==h[2][2]&&0==h[2][3]&&0==h[3][2]&&1==h[3][3]?[h[0][0],h[0][1],h[1][0],h[1][1],h[3][0],h[3][1]]:h[0].concat(h[1],h[2],h[3])}}();a.composeMatrix=b;a.quat=function(b,c,
g){var d=a.dot(b,c),d=Math.max(Math.min(d,1),-1),e=[];if(1===d)e=b;else for(var f=Math.acos(d),h=1*Math.sin(g*f)/Math.sqrt(1-d*d),n=0;4>n;n++)e.push(b[n]*(Math.cos(g*f)-d*h)+c[n]*h);return e}})(m);(function(a,b){function c(a,b,c){this.target=a;this.currentTime=b;this.timelineTime=c;this.type="finish";this.cancelable=this.bubbles=!1;this.currentTarget=a;this.defaultPrevented=!1;this.eventPhase=Event.AT_TARGET;this.timeStamp=Date.now()}a.sequenceNumber=0;b.Animation=function(b){this.id="";b&&b._id&&
(this.id=b._id);this._sequenceNumber=a.sequenceNumber++;this._currentTime=0;this._startTime=null;this._paused=!1;this._playbackRate=1;this._finishedFlag=this._inTimeline=!0;this.onfinish=null;this._finishHandlers=[];this._effect=b;this._inEffect=this._effect._update(0);this._idle=!0;this._currentTimePending=!1};b.Animation.prototype={_ensureAlive:function(){0>this.playbackRate&&0===this.currentTime?this._inEffect=this._effect._update(-1):this._inEffect=this._effect._update(this.currentTime);this._inTimeline||
!this._inEffect&&this._finishedFlag||(this._inTimeline=!0,b.timeline._animations.push(this))},_tickCurrentTime:function(a,b){a!=this._currentTime&&(this._currentTime=a,this._isFinished&&!b&&(this._currentTime=0<this._playbackRate?this._totalDuration:0),this._ensureAlive())},get currentTime(){return this._idle||this._currentTimePending?null:this._currentTime},set currentTime(a){a=+a;isNaN(a)||(b.restart(),this._paused||null==this._startTime||(this._startTime=this._timeline.currentTime-a/this._playbackRate),
this._currentTimePending=!1,this._currentTime!=a&&(this._idle&&(this._idle=!1,this._paused=!0),this._tickCurrentTime(a,!0),b.applyDirtiedAnimation(this)))},get startTime(){return this._startTime},set startTime(a){a=+a;isNaN(a)||this._paused||this._idle||(this._startTime=a,this._tickCurrentTime((this._timeline.currentTime-this._startTime)*this.playbackRate),b.applyDirtiedAnimation(this))},get playbackRate(){return this._playbackRate},set playbackRate(a){if(a!=this._playbackRate){var c=this.currentTime;
this._playbackRate=a;this._startTime=null;"paused"!=this.playState&&"idle"!=this.playState&&(this._finishedFlag=!1,this._idle=!1,this._ensureAlive(),b.applyDirtiedAnimation(this));null!=c&&(this.currentTime=c)}},get _isFinished(){return!this._idle&&(0<this._playbackRate&&this._currentTime>=this._totalDuration||0>this._playbackRate&&0>=this._currentTime)},get _totalDuration(){return this._effect._totalDuration},get playState(){return this._idle?"idle":null==this._startTime&&!this._paused&&0!=this.playbackRate||
this._currentTimePending?"pending":this._paused?"paused":this._isFinished?"finished":"running"},_rewind:function(){if(0<=this._playbackRate)this._currentTime=0;else{if(!(this._totalDuration<1/0))throw new DOMException("Unable to rewind negative playback rate animation with infinite duration","InvalidStateError");this._currentTime=this._totalDuration}},play:function(){this._paused=!1;(this._isFinished||this._idle)&&(this._rewind(),this._startTime=null);this._idle=this._finishedFlag=!1;this._ensureAlive();
b.applyDirtiedAnimation(this)},pause:function(){this._isFinished||this._paused||this._idle?this._idle&&(this._rewind(),this._idle=!1):this._currentTimePending=!0;this._startTime=null;this._paused=!0},finish:function(){this._idle||(this.currentTime=0<this._playbackRate?this._totalDuration:0,this._startTime=this._totalDuration-this.currentTime,this._currentTimePending=!1,b.applyDirtiedAnimation(this))},cancel:function(){this._inEffect&&(this._inEffect=!1,this._idle=!0,this._paused=!1,this._isFinished=
!0,this._finishedFlag=!0,this._currentTime=0,this._startTime=null,this._effect._update(null),b.applyDirtiedAnimation(this))},reverse:function(){this.playbackRate*=-1;this.play()},addEventListener:function(a,b){"function"==typeof b&&"finish"==a&&this._finishHandlers.push(b)},removeEventListener:function(a,b){"finish"==a&&(a=this._finishHandlers.indexOf(b),0<=a&&this._finishHandlers.splice(a,1))},_fireEvents:function(a){if(this._isFinished){if(!this._finishedFlag){var b=new c(this,this._currentTime,
a),g=this._finishHandlers.concat(this.onfinish?[this.onfinish]:[]);setTimeout(function(){g.forEach(function(a){a.call(b.target,b)})},0);this._finishedFlag=!0}}else this._finishedFlag=!1},_tick:function(a,b){this._idle||this._paused||(null==this._startTime?b&&(this.startTime=a-this._currentTime/this.playbackRate):this._isFinished||this._tickCurrentTime((a-this._startTime)*this.playbackRate));b&&(this._currentTimePending=!1,this._fireEvents(a))},get _needsTick(){return this.playState in{pending:1,running:1}||
!this._finishedFlag},_targetAnimations:function(){var a=this._effect._target;return a._activeAnimations||(a._activeAnimations=[]),a._activeAnimations},_markTarget:function(){var a=this._targetAnimations();-1===a.indexOf(this)&&a.push(this)},_unmarkTarget:function(){var a=this._targetAnimations(),b=a.indexOf(this);-1!==b&&a.splice(b,1)}}})(k,m);(function(b,c){function g(a){var b=h;h=[];a<m.currentTime&&(a=m.currentTime);m._animations.sort(d);m._animations=e(a,!0,m._animations)[0];b.forEach(function(b){b[1](a)});
r()}function d(a,b){return a._sequenceNumber-b._sequenceNumber}function k(){this._animations=[];this.currentTime=a.performance&&performance.now?performance.now():0}function r(){x.forEach(function(a){a()});x.length=0}function e(a,b,f){E=!0;p=!1;c.timeline.currentTime=a;u=!1;var e=[],h=[],g=[],d=[];return f.forEach(function(f){f._tick(a,b);f._inEffect?(h.push(f._effect),f._markTarget()):(e.push(f._effect),f._unmarkTarget());f._needsTick&&(u=!0);var c=f._inEffect||f._needsTick;(f._inTimeline=c)?g.push(f):
d.push(f)}),x.push.apply(x,e),x.push.apply(x,h),u&&requestAnimationFrame(function(){}),E=!1,[g,d]}var f=a.requestAnimationFrame,h=[],z=0;a.requestAnimationFrame=function(a){var b=z++;return 0==h.length&&f(g),h.push([b,a]),b};a.cancelAnimationFrame=function(a){h.forEach(function(b){b[0]==a&&(b[1]=function(){})})};k.prototype={_play:function(a){a._timing=b.normalizeTimingInput(a.timing);a=new c.Animation(a);return a._idle=!1,a._timeline=this,this._animations.push(a),c.restart(),c.applyDirtiedAnimation(a),
a}};var u=!1,p=!1;c.restart=function(){return u||(u=!0,requestAnimationFrame(function(){}),p=!0),p};c.applyDirtiedAnimation=function(a){E||(a._markTarget(),a=a._targetAnimations(),a.sort(d),e(c.timeline.currentTime,!1,a.slice())[1].forEach(function(a){a=m._animations.indexOf(a);-1!==a&&m._animations.splice(a,1)}),r())};var x=[],E=!1,m=new k;c.timeline=m})(k,m);(function(a){function b(a,b){for(var f=0,e=0;e<a.length;e++)f+=a[e]*b[e];return f}function c(a,b){return[a[0]*b[0]+a[4]*b[1]+a[8]*b[2]+a[12]*
b[3],a[1]*b[0]+a[5]*b[1]+a[9]*b[2]+a[13]*b[3],a[2]*b[0]+a[6]*b[1]+a[10]*b[2]+a[14]*b[3],a[3]*b[0]+a[7]*b[1]+a[11]*b[2]+a[15]*b[3],a[0]*b[4]+a[4]*b[5]+a[8]*b[6]+a[12]*b[7],a[1]*b[4]+a[5]*b[5]+a[9]*b[6]+a[13]*b[7],a[2]*b[4]+a[6]*b[5]+a[10]*b[6]+a[14]*b[7],a[3]*b[4]+a[7]*b[5]+a[11]*b[6]+a[15]*b[7],a[0]*b[8]+a[4]*b[9]+a[8]*b[10]+a[12]*b[11],a[1]*b[8]+a[5]*b[9]+a[9]*b[10]+a[13]*b[11],a[2]*b[8]+a[6]*b[9]+a[10]*b[10]+a[14]*b[11],a[3]*b[8]+a[7]*b[9]+a[11]*b[10]+a[15]*b[11],a[0]*b[12]+a[4]*b[13]+a[8]*b[14]+
a[12]*b[15],a[1]*b[12]+a[5]*b[13]+a[9]*b[14]+a[13]*b[15],a[2]*b[12]+a[6]*b[13]+a[10]*b[14]+a[14]*b[15],a[3]*b[12]+a[7]*b[13]+a[11]*b[14]+a[15]*b[15]]}function g(a){return 2*((a.deg||0)/360+(a.grad||0)/400+(a.turn||0))*Math.PI+(a.rad||0)}function d(a){switch(a.t){case "rotatex":return a=g(a.d[0]),[1,0,0,0,0,Math.cos(a),Math.sin(a),0,0,-Math.sin(a),Math.cos(a),0,0,0,0,1];case "rotatey":return a=g(a.d[0]),[Math.cos(a),0,-Math.sin(a),0,0,1,0,0,Math.sin(a),0,Math.cos(a),0,0,0,0,1];case "rotate":case "rotatez":return a=
g(a.d[0]),[Math.cos(a),Math.sin(a),0,0,-Math.sin(a),Math.cos(a),0,0,0,0,1,0,0,0,0,1];case "rotate3d":var b=a.d[0],e=a.d[1],c=a.d[2];a=g(a.d[3]);var f=b*b+e*e+c*c;0===f?(b=1,c=e=0):1!==f&&(f=Math.sqrt(f),b/=f,e/=f,c/=f);f=Math.sin(a/2);a=f*Math.cos(a/2);f*=f;return[1-2*(e*e+c*c)*f,2*(b*e*f+c*a),2*(b*c*f-e*a),0,2*(b*e*f-c*a),1-2*(b*b+c*c)*f,2*(e*c*f+b*a),0,2*(b*c*f+e*a),2*(e*c*f-b*a),1-2*(b*b+e*e)*f,0,0,0,0,1];case "scale":return[a.d[0],0,0,0,0,a.d[1],0,0,0,0,1,0,0,0,0,1];case "scalex":return[a.d[0],
0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];case "scaley":return[1,0,0,0,0,a.d[0],0,0,0,0,1,0,0,0,0,1];case "scalez":return[1,0,0,0,0,1,0,0,0,0,a.d[0],0,0,0,0,1];case "scale3d":return[a.d[0],0,0,0,0,a.d[1],0,0,0,0,a.d[2],0,0,0,0,1];case "skew":return b=g(a.d[0]),e=g(a.d[1]),[1,Math.tan(e),0,0,Math.tan(b),1,0,0,0,0,1,0,0,0,0,1];case "skewx":return a=g(a.d[0]),[1,0,0,0,Math.tan(a),1,0,0,0,0,1,0,0,0,0,1];case "skewy":return a=g(a.d[0]),[1,Math.tan(a),0,0,0,1,0,0,0,0,1,0,0,0,0,1];case "translate":return b=a.d[0].px||
0,e=a.d[1].px||0,[1,0,0,0,0,1,0,0,0,0,1,0,b,e,0,1];case "translatex":return b=a.d[0].px||0,[1,0,0,0,0,1,0,0,0,0,1,0,b,0,0,1];case "translatey":return e=a.d[0].px||0,[1,0,0,0,0,1,0,0,0,0,1,0,0,e,0,1];case "translatez":return c=a.d[0].px||0,[1,0,0,0,0,1,0,0,0,0,1,0,0,0,c,1];case "translate3d":return b=a.d[0].px||0,e=a.d[1].px||0,c=a.d[2].px||0,[1,0,0,0,0,1,0,0,0,0,1,0,b,e,c,1];case "perspective":return[1,0,0,0,0,1,0,0,0,0,1,a.d[0].px?-1/a.d[0].px:0,0,0,0,1];case "matrix":return[a.d[0],a.d[1],0,0,a.d[2],
a.d[3],0,0,0,0,1,0,a.d[4],a.d[5],0,1];case "matrix3d":return a.d}}function k(a){return 0===a.length?[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]:a.map(d).reduce(c)}var e=function(){function a(a){return a[0][0]*a[1][1]*a[2][2]+a[1][0]*a[2][1]*a[0][2]+a[2][0]*a[0][1]*a[1][2]-a[0][2]*a[1][1]*a[2][0]-a[1][2]*a[2][1]*a[0][0]-a[2][2]*a[0][1]*a[1][0]}function e(a){var b=c(a);return[a[0]/b,a[1]/b,a[2]/b]}function c(a){return Math.sqrt(a[0]*a[0]+a[1]*a[1]+a[2]*a[2])}function g(a,b,e){return[1*a[0]+e*b[0],1*a[1]+e*b[1],
1*a[2]+e*b[2]]}return function(f){f=[f.slice(0,4),f.slice(4,8),f.slice(8,12),f.slice(12,16)];if(1!==f[3][3])return null;for(var d=[],h=0;4>h;h++)d.push(f[h].slice());for(h=0;3>h;h++)d[h][3]=0;if(0===a(d))return null;var k;k=[];if(f[0][3]||f[1][3]||f[2][3]){k.push(f[0][3]);k.push(f[1][3]);k.push(f[2][3]);k.push(f[3][3]);for(var l=1/a(d),r=d[0][0],n=d[0][1],h=d[0][2],p=d[1][0],u=d[1][1],m=d[1][2],z=d[2][0],A=d[2][1],q=d[2][2],l=[[(u*q-m*A)*l,(h*A-n*q)*l,(n*m-h*u)*l,0],[(m*z-p*q)*l,(r*q-h*z)*l,(h*p-
r*m)*l,0],[(p*A-u*z)*l,(z*n-r*A)*l,(r*u-n*p)*l,0]],r=[],n=0;3>n;n++){for(p=h=0;3>p;p++)h+=d[3][p]*l[p][n];r.push(h)}d=(r.push(1),l.push(r),l);d=[[d[0][0],d[1][0],d[2][0],d[3][0]],[d[0][1],d[1][1],d[2][1],d[3][1]],[d[0][2],d[1][2],d[2][2],d[3][2]],[d[0][3],d[1][3],d[2][3],d[3][3]]];l=[];for(r=0;4>r;r++){for(h=n=0;4>h;h++)n+=k[h]*d[h][r];l.push(n)}k=l}else k=[0,0,0,1];d=f[3].slice(0,3);l=[];l.push(f[0].slice(0,3));r=[];r.push(c(l[0]));l[0]=e(l[0]);n=[];l.push(f[1].slice(0,3));n.push(b(l[0],l[1]));l[1]=
g(l[1],l[0],-n[0]);r.push(c(l[1]));l[1]=e(l[1]);n[0]/=r[1];l.push(f[2].slice(0,3));n.push(b(l[0],l[2]));l[2]=g(l[2],l[0],-n[1]);n.push(b(l[1],l[2]));l[2]=g(l[2],l[1],-n[2]);r.push(c(l[2]));l[2]=e(l[2]);n[1]/=r[2];n[2]/=r[2];f=l[1];h=l[2];if(0>b(l[0],[f[1]*h[2]-f[2]*h[1],f[2]*h[0]-f[0]*h[2],f[0]*h[1]-f[1]*h[0]]))for(h=0;3>h;h++)r[h]*=-1,l[h][0]*=-1,l[h][1]*=-1,l[h][2]*=-1;var y,w;f=l[0][0]+l[1][1]+l[2][2]+1;return 1E-4<f?(y=.5/Math.sqrt(f),w=[(l[2][1]-l[1][2])*y,(l[0][2]-l[2][0])*y,(l[1][0]-l[0][1])*
y,.25/y]):l[0][0]>l[1][1]&&l[0][0]>l[2][2]?(y=2*Math.sqrt(1+l[0][0]-l[1][1]-l[2][2]),w=[.25*y,(l[0][1]+l[1][0])/y,(l[0][2]+l[2][0])/y,(l[2][1]-l[1][2])/y]):l[1][1]>l[2][2]?(y=2*Math.sqrt(1+l[1][1]-l[0][0]-l[2][2]),w=[(l[0][1]+l[1][0])/y,.25*y,(l[1][2]+l[2][1])/y,(l[0][2]-l[2][0])/y]):(y=2*Math.sqrt(1+l[2][2]-l[0][0]-l[1][1]),w=[(l[0][2]+l[2][0])/y,(l[1][2]+l[2][1])/y,.25*y,(l[1][0]-l[0][1])/y]),[d,r,n,w,k]}}();a.dot=b;a.makeMatrixDecomposition=function(a){return[e(k(a))]};a.transformListToMatrix=
k})(m);(function(a){function b(a,b){var e=a.exec(b);if(e)return e=a.ignoreCase?e[0].toLowerCase():e[0],[e,b.substr(e.length)]}function c(a,b){b=b.replace(/^\s*/,"");if(a=a(b))return[a[0],a[1].replace(/^\s*/,"")]}function d(a,b){for(var e=a,c=b;e&&c;)e>c?e%=c:c%=e;return a*b/(e+c)}function g(a,b,c,g,l){for(var e=[],f=[],h=[],k=d(g.length,l.length),n=0;n<k;n++){var r=b(g[n%g.length],l[n%l.length]);if(!r)return;e.push(r[0]);f.push(r[1]);h.push(r[2])}return[e,f,function(b){b=b.map(function(a,b){return h[b](a)}).join(c);
return a?a(b):b}]}a.consumeToken=b;a.consumeTrimmed=c;a.consumeRepeated=function(a,e,f){a=c.bind(null,a);for(var d=[];;){var g=a(f);if(!g||(d.push(g[0]),f=g[1],!(g=b(e,f))||""==g[1]))return[d,f];f=g[1]}};a.consumeParenthesised=function(a,b){for(var e=0,c=0;c<b.length&&(!/\s|,/.test(b[c])||0!=e);c++)if("("==b[c])e++;else if(")"==b[c]&&(e--,0==e&&c++,0>=e))break;a=a(b.substr(0,c));return void 0==a?void 0:[a,b.substr(c)]};a.ignore=function(a){return function(b){b=a(b);return b&&(b[0]=void 0),b}};a.optional=
function(a,b){return function(e){return a(e)||[b,e]}};a.consumeList=function(b,e){for(var c=[],d=0;d<b.length;d++){e=a.consumeTrimmed(b[d],e);if(!e||""==e[0])return;void 0!==e[0]&&c.push(e[0]);e=e[1]}if(""==e)return c};a.mergeNestedRepeated=g.bind(null,null);a.mergeWrappedNestedRepeated=g;a.mergeList=function(a,b,c){for(var e=[],f=[],d=[],g=0,l=0;l<c.length;l++)if("function"==typeof c[l]){var k=c[l](a[g],b[g++]);e.push(k[0]);f.push(k[1]);d.push(k[2])}else!function(a){e.push(!1);f.push(!1);d.push(function(){return c[a]})}(l);
return[e,f,function(a){for(var b="",e=0;e<a.length;e++)b+=d[e](a[e]);return b}]}})(m);(function(a){function b(b){var c={inset:!1,lengths:[],color:null};if((b=a.consumeRepeated(function(b){var e=a.consumeToken(/^inset/i,b);return e?(c.inset=!0,e):(e=a.consumeLengthOrPercent(b))?(c.lengths.push(e[0]),e):(e=a.consumeColor(b))?(c.color=e[0],e):void 0},/^/,b))&&b[0].length)return[c,b[1]]}var c=function(b,c,d,e){function f(a){return{inset:a,color:[0,0,0,0],lengths:[{px:0},{px:0},{px:0},{px:0}]}}for(var g=
[],l=[],k=0;k<d.length||k<e.length;k++){var n=d[k]||f(e[k].inset),r=e[k]||f(d[k].inset);g.push(n);l.push(r)}return a.mergeNestedRepeated(b,c,g,l)}.bind(null,function(b,c){for(;b.lengths.length<Math.max(b.lengths.length,c.lengths.length);)b.lengths.push({px:0});for(;c.lengths.length<Math.max(b.lengths.length,c.lengths.length);)c.lengths.push({px:0});if(b.inset==c.inset&&!!b.color==!!c.color){for(var d,e=[],f=[[],0],g=[[],0],l=0;l<b.lengths.length;l++){var k=a.mergeDimensions(b.lengths[l],c.lengths[l],
2==l);f[0].push(k[0]);g[0].push(k[1]);e.push(k[2])}b.color&&c.color&&(c=a.mergeColors(b.color,c.color),f[1]=c[0],g[1]=c[1],d=c[2]);return[f,g,function(a){for(var c=b.inset?"inset ":" ",f=0;f<e.length;f++)c+=e[f](a[0][f])+" ";return d&&(c+=d(a[1])),c}]}},", ");a.addPropertiesHandler(function(c){if((c=a.consumeRepeated(b,/^,/,c))&&""==c[1])return c[0]},c,["box-shadow","text-shadow"])})(m);(function(a){function b(a){return a.toFixed(3).replace(/0+$/,"").replace(/\.$/,"")}function c(a,b,c){return Math.min(b,
Math.max(a,c))}function d(a){if(/^\s*[-+]?(\d*\.)?\d+\s*$/.test(a))return Number(a)}function g(a){return function(e,d){return[e,d,function(e){return b(c(0,a,e))}]}}function k(a){a=a.trim().split(/\s*[\s,]\s*/);if(0!==a.length){for(var b=[],c=0;c<a.length;c++){var e=d(a[c]);if(void 0===e)return;b.push(e)}return b}}a.clamp=c;a.addPropertiesHandler(k,function(a,c){if(a.length==c.length)return[a,c,function(a){return a.map(b).join(" ")}]},["stroke-dasharray"]);a.addPropertiesHandler(d,g(1/0),["border-image-width",
"line-height"]);a.addPropertiesHandler(d,g(1),["opacity","shape-image-threshold"]);a.addPropertiesHandler(d,function(a,b){if(0!=a)return g(1/0)(a,b)},["flex-grow","flex-shrink"]);a.addPropertiesHandler(d,function(a,b){return[a,b,function(a){return Math.round(c(1,1/0,a))}]},["orphans","widows"]);a.addPropertiesHandler(d,function(a,b){return[a,b,Math.round]},["z-index"]);a.parseNumber=d;a.parseNumberList=k;a.mergeNumbers=function(a,c){return[a,c,b]};a.numberToString=b})(m);(function(a){a.addPropertiesHandler(String,
function(a,b){if("visible"==a||"visible"==b)return[0,1,function(c){return 0>=c?a:1<=c?b:"visible"}]},["visibility"])})(m);(function(a){function c(a){a=a.trim();l.fillStyle="#000";l.fillStyle=a;var b=l.fillStyle;if(l.fillStyle="#fff",l.fillStyle=a,b==l.fillStyle)return l.fillRect(0,0,1,1),a=l.getImageData(0,0,1,1).data,l.clearRect(0,0,1,1),b=a[3]/255,[a[0]*b,a[1]*b,a[2]*b,b]}function d(b,c){return[b,c,function(b){if(b[3])for(var c=0;3>c;c++)b[c]=Math.round(Math.max(0,Math.min(255,b[c]/b[3])));return b[3]=
a.numberToString(a.clamp(0,1,b[3])),"rgba("+b.join(",")+")"}]}var g=b.createElementNS("http://www.w3.org/1999/xhtml","canvas");g.width=g.height=1;var l=g.getContext("2d");a.addPropertiesHandler(c,d,"background-color border-bottom-color border-left-color border-right-color border-top-color color fill flood-color lighting-color outline-color stop-color stroke text-decoration-color".split(" "));a.consumeColor=a.consumeParenthesised.bind(null,c);a.mergeColors=d})(m);(function(a){function b(a){function b(){var b=
g.exec(a);d=b?b[0]:void 0}function c(){if("("!==d){var a=Number(d);return b(),a}b();a=f();return")"!==d?NaN:(b(),a)}function e(){for(var a=c();"*"===d||"/"===d;){var e=d;b();var f=c();"*"===e?a*=f:a/=f}return a}function f(){for(var a=e();"+"===d||"-"===d;){var c=d;b();var f=e();"+"===c?a+=f:a-=f}return a}var d,g=/([\+\-\w\.]+|[\(\)\*\/])/g;return b(),f()}function c(a,c){if("0"==(c=c.trim().toLowerCase())&&0<="px".search(a))return{px:0};if(/^[^(]*$|^calc/.test(c)){c=c.replace(/calc\(/g,"(");var e=
{};c=c.replace(a,function(a){return e[a]=null,"U"+a});a="U("+a.source+")";for(var f=c.replace(/[-+]?(\d*\.)?\d+([Ee][-+]?\d+)?/g,"N").replace(new RegExp("N"+a,"g"),"D").replace(/\s[+-]\s/g,"O").replace(/\s/g,""),d=[/N\*(D)/g,/(N|D)[*\/]N/g,/(N|D)O\1/g,/\((N|D)\)/g],g=0;g<d.length;)d[g].test(f)?(f=f.replace(d[g],"$1"),g=0):g++;if("D"==f){for(var h in e){f=b(c.replace(new RegExp("U"+h,"g"),"").replace(new RegExp(a,"g"),"*0"));if(!isFinite(f))return;e[h]=f}return e}}}function d(a,b){return g(a,b,!0)}
function g(b,c,e){var f,d=[];for(f in b)d.push(f);for(f in c)0>d.indexOf(f)&&d.push(f);return b=d.map(function(a){return b[a]||0}),c=d.map(function(a){return c[a]||0}),[b,c,function(b){var c=b.map(function(c,f){return 1==b.length&&e&&(c=Math.max(c,0)),a.numberToString(c)+d[f]}).join(" + ");return 1<b.length?"calc("+c+")":c}]}var k=c.bind(null,/px|em|ex|ch|rem|vw|vh|vmin|vmax|cm|mm|in|pt|pc/g),e=c.bind(null,/px|em|ex|ch|rem|vw|vh|vmin|vmax|cm|mm|in|pt|pc|%/g),f=c.bind(null,/deg|rad|grad|turn/g);a.parseLength=
k;a.parseLengthOrPercent=e;a.consumeLengthOrPercent=a.consumeParenthesised.bind(null,e);a.parseAngle=f;a.mergeDimensions=g;var k=a.consumeParenthesised.bind(null,k),k=a.consumeRepeated.bind(void 0,k,/^/),h=a.consumeRepeated.bind(void 0,k,/^,/);a.consumeSizePairList=h;k=a.mergeNestedRepeated.bind(void 0,d," ");f=a.mergeNestedRepeated.bind(void 0,k,",");a.mergeNonNegativeSizePair=k;a.addPropertiesHandler(function(a){if((a=h(a))&&""==a[1])return a[0]},f,["background-size"]);a.addPropertiesHandler(e,
d,"border-bottom-width border-image-width border-left-width border-right-width border-top-width flex-basis font-size height line-height max-height max-width outline-width width".split(" "));a.addPropertiesHandler(e,g,"border-bottom-left-radius border-bottom-right-radius border-top-left-radius border-top-right-radius bottom left letter-spacing margin-bottom margin-left margin-right margin-top min-height min-width outline-offset padding-bottom padding-left padding-right padding-top perspective right shape-margin stroke-dashoffset text-indent top vertical-align word-spacing".split(" "))})(m);
(function(a){function b(b){return a.consumeLengthOrPercent(b)||a.consumeToken(/^auto/,b)}function c(c){if((c=a.consumeList([a.ignore(a.consumeToken.bind(null,/^rect/)),a.ignore(a.consumeToken.bind(null,/^\(/)),a.consumeRepeated.bind(null,b,/^,/),a.ignore(a.consumeToken.bind(null,/^\)/))],c))&&4==c[0].length)return c[0]}var d=a.mergeWrappedNestedRepeated.bind(null,function(a){return"rect("+a+")"},function(b,c){return"auto"==b||"auto"==c?[!0,!1,function(e){e=e?b:c;if("auto"==e)return"auto";e=a.mergeDimensions(e,
e);return e[2](e[0])}]:a.mergeDimensions(b,c)},", ");a.parseBox=c;a.mergeBoxes=d;a.addPropertiesHandler(c,d,["clip"])})(m);(function(a){function b(a){return function(b){var c=0;return a.map(function(a){return a===f?b[c++]:a})}}function c(a){return a}function d(b){if("none"==(b=b.toLowerCase().trim()))return[];for(var c,e=/\s*(\w+)\(([^)]*)\)/g,f=[],d=0;(c=e.exec(b))&&c.index==d;){var d=c.index+c[0].length,g=c[1],l=q[g];if(!l)break;c=c[2].split(",");l=l[0];if(l.length<c.length)break;for(var k=[],n=
0;n<l.length;n++){var p;p=c[n];var r=l[n];if(void 0===(p=p?{A:function(b){return"0"==b.trim()?m:a.parseAngle(b)},N:a.parseNumber,T:a.parseLengthOrPercent,L:a.parseLength}[r.toUpperCase()](p):{a:m,n:k[0],t:h}[r]))return;k.push(p)}if(f.push({t:g,d:k}),e.lastIndex==b.length)return f}}function g(a){return a.toFixed(6).replace(".000000","")}function k(b,c){if(b.decompositionPair!==c){b.decompositionPair=c;var e=a.makeMatrixDecomposition(b)}if(c.decompositionPair!==b){c.decompositionPair=b;var f=a.makeMatrixDecomposition(c)}return null==
e[0]||null==f[0]?[[!1],[!0],function(a){return a?c[0].d:b[0].d}]:(e[0].push(0),f[0].push(1),[e,f,function(b){var c=a.quat(e[0][3],f[0][3],b[5]);return a.composeMatrix(b[0],b[1],b[2],c,b[4]).map(g).join(",")}])}function e(a){return a.replace(/(x|y|z|3d)?$/,"3d")}var f=null,h={px:0},m={deg:0},q={matrix:["NNNNNN",[f,f,0,0,f,f,0,0,0,0,1,0,f,f,0,1],c],matrix3d:["NNNNNNNNNNNNNNNN",c],rotate:["A"],rotatex:["A"],rotatey:["A"],rotatez:["A"],rotate3d:["NNNA"],perspective:["L"],scale:["Nn",b([f,f,1]),c],scalex:["N",
b([f,1,1]),b([f,1])],scaley:["N",b([1,f,1]),b([1,f])],scalez:["N",b([1,1,f])],scale3d:["NNN",c],skew:["Aa",null,c],skewx:["A",null,b([f,m])],skewy:["A",null,b([m,f])],translate:["Tt",b([f,f,h]),c],translatex:["T",b([f,h,h]),b([f,h])],translatey:["T",b([h,f,h]),b([h,f])],translatez:["L",b([h,h,f])],translate3d:["TTL",c]};a.addPropertiesHandler(d,function(b,c){var f=a.makeMatrixDecomposition&&!0,d=!1;if(!b.length||!c.length){b.length||(d=!0,b=c,c=[]);for(var g=0;g<b.length;g++){var h=b[g].t,l=b[g].d,
n="scale"==h.substr(0,5)?1:0;c.push({t:h,d:l.map(function(a){if("number"==typeof a)return n;var b={},c;for(c in a)b[c]=n;return b})})}}var l=[],m=[],r=[];if(b.length!=c.length){if(!f)return;var p=k(b,c),l=[p[0]],m=[p[1]],r=[["matrix",[p[2]]]]}else for(g=0;g<b.length;g++){var h=b[g].t,u=c[g].t,A=b[g].d,w=c[g].d,p=q[h],x=q[u];if("perspective"==h&&"perspective"==u||!("matrix"!=h&&"matrix3d"!=h||"matrix"!=u&&"matrix3d"!=u)){if(!f)return;p=k([b[g]],[c[g]]);l.push(p[0]);m.push(p[1]);r.push(["matrix",[p[2]]])}else{if(h!=
u)if(p[2]&&x[2]&&h.replace(/[xy]/,"")==u.replace(/[xy]/,""))h=h.replace(/[xy]/,""),A=p[2](A),w=x[2](w);else{if(!p[1]||!x[1]||e(h)!=e(u)){if(!f)return;p=k(b,c);l=[p[0]];m=[p[1]];r=[["matrix",[p[2]]]];break}h=e(h);A=p[1](A);w=x[1](w)}for(var x=[],u=[],y=[],z=0;z<A.length;z++)p=("number"==typeof A[z]?a.mergeNumbers:a.mergeDimensions)(A[z],w[z]),x[z]=p[0],u[z]=p[1],y.push(p[2]);l.push(x);m.push(u);r.push([h,y])}}d&&(b=l,l=m,m=b);return[l,m,function(a){return a.map(function(a,b){a=a.map(function(a,c){return r[b][1][c](a)}).join(",");
return"matrix"==r[b][0]&&16==a.split(",").length&&(r[b][0]="matrix3d"),r[b][0]+"("+a+")"}).join(" ")}]},["transform"]);a.transformToSvgMatrix=function(b){b=a.transformListToMatrix(d(b));return"matrix("+g(b[0])+" "+g(b[1])+" "+g(b[4])+" "+g(b[5])+" "+g(b[12])+" "+g(b[13])+")"}})(m);(function(a){function b(b){return b=100*Math.round(b/100),b=a.clamp(100,900,b),400===b?"normal":700===b?"bold":String(b)}a.addPropertiesHandler(function(a){a=Number(a);if(!(isNaN(a)||100>a||900<a||0!=a%100))return a},function(a,
c){return[a,c,b]},["font-weight"])})(m);(function(a){function b(b){return a.consumeToken(/^(left|center|right|top|bottom)\b/i,b)||a.consumeLengthOrPercent(b)}function c(c,f){if((f=a.consumeRepeated(b,/^/,f))&&""==f[1]&&(f=f[0],f[0]=f[0]||"center",f[1]=f[1]||"center",3==c&&(f[2]=f[2]||{px:0}),f.length==c)){if(/top|bottom/.test(f[0])||/left|right/.test(f[1]))c=f[0],f[0]=f[1],f[1]=c;if(/left|right|center|Object/.test(f[0])&&/top|bottom|center|Object/.test(f[1]))return f.map(function(a){return"object"==
typeof a?a:g[a]})}}function d(c){if(c=a.consumeRepeated(b,/^/,c)){for(var e=c[0],d=[{"%":50},{"%":50}],l=0,k=!1,n=0;n<e.length;n++){var m=e[n];if("string"==typeof m)k=/bottom|right/.test(m),l={left:0,right:0,center:l,top:1,bottom:1}[m],d[l]=g[m],"center"==m&&l++;else{if(k){var k=void 0,r={};for(k in m)r[k]=-m[k];m=r;m["%"]=(m["%"]||0)+100}d[l]=m;l++;k=!1}}return[d,c[1]]}}var g={left:{"%":0},center:{"%":50},right:{"%":100},top:{"%":0},bottom:{"%":100}},k=a.mergeNestedRepeated.bind(null,a.mergeDimensions,
" ");a.addPropertiesHandler(c.bind(null,3),k,["transform-origin"]);a.addPropertiesHandler(c.bind(null,2),k,["perspective-origin"]);a.consumePosition=d;a.mergeOffsetList=k;k=a.mergeNestedRepeated.bind(null,k,", ");a.addPropertiesHandler(function(b){if((b=a.consumeRepeated(d,/^,/,b))&&""==b[1])return b[0]},k,["background-position","object-position"])})(m);(function(a){var b=a.consumeParenthesised.bind(null,a.parseLengthOrPercent),c=a.consumeRepeated.bind(void 0,b,/^/),d=a.mergeNestedRepeated.bind(void 0,
a.mergeDimensions," "),g=a.mergeNestedRepeated.bind(void 0,d,",");a.addPropertiesHandler(function(d){var e=a.consumeToken(/^circle/,d);return e&&e[0]?["circle"].concat(a.consumeList([a.ignore(a.consumeToken.bind(void 0,/^\(/)),b,a.ignore(a.consumeToken.bind(void 0,/^at/)),a.consumePosition,a.ignore(a.consumeToken.bind(void 0,/^\)/))],e[1])):(e=a.consumeToken(/^ellipse/,d))&&e[0]?["ellipse"].concat(a.consumeList([a.ignore(a.consumeToken.bind(void 0,/^\(/)),c,a.ignore(a.consumeToken.bind(void 0,/^at/)),
a.consumePosition,a.ignore(a.consumeToken.bind(void 0,/^\)/))],e[1])):(d=a.consumeToken(/^polygon/,d))&&d[0]?["polygon"].concat(a.consumeList([a.ignore(a.consumeToken.bind(void 0,/^\(/)),a.optional(a.consumeToken.bind(void 0,/^nonzero\s*,|^evenodd\s*,/),"nonzero,"),a.consumeSizePairList,a.ignore(a.consumeToken.bind(void 0,/^\)/))],d[1])):void 0},function(b,c){if(b[0]===c[0])return"circle"==b[0]?a.mergeList(b.slice(1),c.slice(1),["circle(",a.mergeDimensions," at ",a.mergeOffsetList,")"]):"ellipse"==
b[0]?a.mergeList(b.slice(1),c.slice(1),["ellipse(",a.mergeNonNegativeSizePair," at ",a.mergeOffsetList,")"]):"polygon"==b[0]&&b[1]==c[1]?a.mergeList(b.slice(2),c.slice(2),["polygon(",b[1],g,")"]):void 0},["shape-outside"])})(m);(function(a){function c(a,c){c.concat([a]).forEach(function(c){c in b.documentElement.style&&(d[a]=c);g[c]=a})}var d={},g={};c("transform",["webkitTransform","msTransform"]);c("transformOrigin",["webkitTransformOrigin"]);c("perspective",["webkitPerspective"]);c("perspectiveOrigin",
["webkitPerspectiveOrigin"]);a.propertyName=function(a){return d[a]||a};a.unprefixedPropertyName=function(a){return g[a]||a}})(m)})();(function(){if(void 0===b.createElement("div").animate([]).oncancel){var c;c=a.performance&&performance.now?function(){return performance.now()}:function(){return Date.now()};var d=function(a,b){this.target=a;this.currentTime=null;this.timelineTime=b;this.type="cancel";this.cancelable=this.bubbles=!1;this.currentTarget=a;this.defaultPrevented=!1;this.eventPhase=Event.AT_TARGET;
this.timeStamp=Date.now()},g=a.Element.prototype.animate;a.Element.prototype.animate=function(a,b){a=g.call(this,a,b);a._cancelHandlers=[];a.oncancel=null;var k=a.cancel;a.cancel=function(){k.call(this);var a=new d(this,c()),b=this._cancelHandlers.concat(this.oncancel?[this.oncancel]:[]);setTimeout(function(){b.forEach(function(b){b.call(a.target,a)})},0)};var l=a.addEventListener;a.addEventListener=function(a,b){"function"==typeof b&&"cancel"==a?this._cancelHandlers.push(b):l.call(this,a,b)};var m=
a.removeEventListener;return a.removeEventListener=function(a,b){"cancel"==a?(a=this._cancelHandlers.indexOf(b),0<=a&&this._cancelHandlers.splice(a,1)):m.call(this,a,b)},a}}})();(function(c){var d=b.documentElement,g=null,k=!1;try{var m="0"==getComputedStyle(d).getPropertyValue("opacity")?"1":"0",g=d.animate({opacity:[m,m]},{duration:1});g.currentTime=0;k=getComputedStyle(d).getPropertyValue("opacity")==m}catch(l){}finally{g&&g.cancel()}if(!k){var n=a.Element.prototype.animate;a.Element.prototype.animate=
function(b,d){return a.Symbol&&Symbol.iterator&&Array.prototype.from&&b[Symbol.iterator]&&(b=Array.from(b)),Array.isArray(b)||null===b||(b=c.convertToArrayForm(b)),n.call(this,b,d)}}})(k);d.true=c}({},function(){return this}())};function Yb(a){a.__AMP_WA||(a.__AMP_WA=!0,Xb(a))};function Zb(a){this.ea=a;this.sa=ua(a.win,"vsync");this.ma=wa(a,"resources")}Zb.prototype.createBuilder=function(){Yb(this.ea.win);return new Gb(this.ea.win,this.ea.getRootNode(),this.ea.getUrl(),this.sa,this.ma)};function $b(a){a=AMP.BaseElement.call(this,a)||this;a.pa=!1;a.H=!1;a.D=!1;a.o=!1;a.F=null;a.ja=null;a.m=null;a.V=null;a.Ea=null;return a}C($b,AMP.BaseElement);t=$b.prototype;
t.buildCallback=function(){var a=this,b=this.getAmpDoc(),c=this.element.getAttribute("trigger");c&&(this.pa=I().assert("visibility"==c,'Only allowed value for "trigger" is "visibility": %s',this.element));"visibility"==c&&I().assert(this.element.parentNode==this.element.ownerDocument.body||this.element.parentNode==b.getBody(),"amp-animation is only allowed as a direct child of <body> element when trigger is visibility. This restriction will be removed soon.");var d=I().assert(Ga(this.element),'"<script type=application/json>" must be present');
this.ja=ta(d.textContent,function(a){throw I().createError("failed to parse animation script",a);});this.pa&&this.mutateElement(function(){Ka(a.element,{visibility:"hidden",top:"0px",left:"0px",width:"1px",height:"1px",display:"block",position:"fixed"})});this.Ea=new Wb(this.win,function(){a.D||ac(a)},50);var k=ya(this.element,b.win),m=k?k.__AMP_EMBED__:null;if(m)this.F=m,this.$(m.isVisible()),m.onVisibilityChanged(function(){a.$(m.isVisible())}),Oa(this.F.win,function(){return bc(a)});else{var q=
wa(b,"viewer");this.$(q.isVisible());q.onVisibilityChanged(function(){a.$(q.isVisible())});this.getViewport().onResize(function(b){b.relayoutAll&&bc(a)})}this.registerAction("start",this.oa.bind(this),1);this.registerAction("restart",this.Sa.bind(this),1);this.registerAction("pause",this.Qa.bind(this),1);this.registerAction("resume",this.Ta.bind(this),1);this.registerAction("togglePause",this.Ya.bind(this),1);this.registerAction("seekTo",this.Va.bind(this),1);this.registerAction("reverse",this.Ua.bind(this),
1);this.registerAction("finish",this.Oa.bind(this),1);this.registerAction("cancel",this.La.bind(this),1)};t.getAnimationSpec=function(){return this.ja};t.layoutCallback=function(){this.pa&&this.oa();return Promise.resolve()};t.pauseCallback=function(){this.$(!1)};t.activate=function(a){return this.oa(a)};t.oa=function(a){this.o=!0;return this.H?ac(this,a?a.args:null):Promise.resolve()};t.Sa=function(a){cc(this);this.o=!0;return this.H?ac(this,a.args):Promise.resolve()};
t.Qa=function(){var a=this;return this.o?dc(this).then(function(){ec(a);a.D=!0}):Promise.resolve()};t.Ta=function(){var a=this;return this.o?dc(this).then(function(){a.H&&(a.m.resume(),a.D=!1)}):Promise.resolve()};t.Ya=function(){var a=this;return this.o?dc(this).then(function(){if(a.H){if("paused"==a.m.getPlayState())return ac(a);ec(a);a.D=!0}}):Promise.resolve()};
t.Va=function(a){var b=this;this.o=!0;return dc(this).then(function(){ec(b);b.D=!0;var c=parseFloat(a.args&&a.args.time);"number"===typeof c&&isFinite(c)&&b.m.seekTo(c);c=parseFloat(a.args&&a.args.percent);"number"===typeof c&&isFinite(c)&&b.m.seekToPercent(Ra(c))})};t.Ua=function(){var a=this;return this.o?dc(this).then(function(){a.H&&a.m.reverse()}):Promise.resolve()};t.Oa=function(){fc(this);return Promise.resolve()};t.La=function(){cc(this);return Promise.resolve()};
t.$=function(a){this.H!=a&&(this.H=a,this.o&&(this.H?this.D||ac(this):ec(this)))};function bc(a){var b=a.o,c=a.D;a.m&&(a.m.cancel(),a.m=null,a.V=null);a.o=b;a.D=c;a.o&&a.H&&a.Ea.schedule()}function ac(a,b){if(!a.o||!a.H)return null;a.D=!1;return a.m?(a.m.resume(),null):dc(a,b).then(function(){a.m.start()})}function dc(a,b){a.V||(a.V=gc(a,b).then(function(b){a.m=b;a.m.onPlayStateChanged(a.Ra.bind(a));a.m.init()}));return a.V}function fc(a){a.o=!1;a.D=!1;a.m&&(a.m.finish(),a.m=null,a.V=null)}
function cc(a){a.o=!1;a.D=!1;a.m&&(a.m.cancel(),a.m=null,a.V=null)}function gc(a,b){var c=a.ja,d=b||null;Yb(a.win);b=a.getAmpDoc();var k=a.F?a.F.whenReady():b.whenReady(),m=a.F?a.F.win:a.win,q=a.F?a.F.getUrl():b.getUrl();return k.then(function(){return(new Gb(m,a.F?a.F.win.document:a.getAmpDoc().getRootNode(),q,a.getVsync(),a.element.getResources())).createRunner(c,d)})}function ec(a){a.m&&a.m.pause()}t.Ra=function(a){"finished"==a&&fc(this)};
(function(a){a.registerElement("amp-animation",$b);a.registerServiceForDoc("web-animation",Zb)})(self.AMP);
})});
//# sourceMappingURL=amp-animation-0.1.js.map

