(self.AMP=self.AMP||[]).push({n:"amp-list",v:"1524862012167",f:(function(AMP){function f(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};self.log=self.log||{user:null,dev:null,userForEmbed:null};var g=self.log;function k(){if(!g.user)throw Error("failed to call initLogConstructor");return g.user}function m(){if(g.dev)return g.dev;throw Error("failed to call initLogConstructor");};function n(a){this.H=a;this.j=Object.create(null)}n.prototype.get=function(a){if(this.j[a])return this.j[a].access=Date.now(),this.j[a].payload};n.prototype.put=function(a,b){var c=this;this.j[a]={payload:b,access:Date.now()};var d=Object.keys(this.j);d.length>this.H&&(m().warn("lru-cache","Trimming template cache"),d.sort(function(a,b){return c.j[b].access-c.j[a].access}),delete this.j[d[d.length-1]])};var p=self.AMP_CONFIG||{},q=("string"==typeof p.cdnProxyRegex?new RegExp(p.cdnProxyRegex):p.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;var r={c:!0,v:!0,a:!0,ad:!0},t,u,v=/[?&]amp_js[^&]*/,w=/[?&]usqp[^&]*/;
function x(a){var b;t||(t=self.document.createElement("a"),u=self.UrlCache||(self.UrlCache=new n(100)));var c=u.get(a);if(c)return c;var d=t;d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=d.origin&&
"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;var h=e,l=h;if(b)return l;u.put(a,l);return l}function y(a){"string"==typeof a&&(a=x(a));var b;(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}
function z(a,b){var c;c=void 0===c?"source":c;k().assert(null!=a,"%s %s must be available",b,c);var d=a;k().assert(y(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d);return d}
function A(a){"string"==typeof a&&(a=x(a));var b=a;"string"==typeof b&&(b=x(b));if(!q.test(b.origin))return a.href;var b=a.pathname.split("/"),c=b[1];k().assert(r[c],"Unknown path prefix in url %s",a.href);var d=b[2],e="s"==d?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(d);k().assert(0<e.indexOf("."),"Expected a . in origin %s",e);b.splice(1,"s"==d?3:2);b=e+b.join("/");c=(c=a.search)&&"?"!=c?(c=c.replace(v,"").replace(w,"").replace(/^[?&]/,""))?"?"+c:"":"";return b+c+(a.hash||
"")};function B(a,b,c){if(a.nodeType){var d=(a.ownerDocument||a).defaultView;if(d=d!=(d.__AMP_TOP||d)&&C(d,b)?D(d,b):null)return d}!a.nodeType||c?(c=E(a),c=F(c),b=D(c,b)):b=null;return b}function G(a,b){a=a.__AMP_TOP||a;return D(a,b)}function E(a){return a.nodeType?G((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function F(a){a=E(a);return a.isSingleDoc()?a.win:a}
function D(a,b){C(a,b);var c=H(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function I(a){var b=J(a);if(b)return b;var c,d=new Promise(function(a){c=a});H(a).bind={obj:null,promise:d,resolve:c,context:null,ctor:null};return d}function J(a){var b=H(a).bind;if(b){if(b.promise)return b.promise;D(a,"bind");return b.promise=Promise.resolve(b.obj)}return null}function H(a){var b=a.services;b||(b=a.services={});return b}
function C(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function K(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var h=d.setInterval(function(){b(a)&&(d.clearInterval(h),c())},5)}}function L(a,b){K(a.documentElement,function(){return!!a.body},b)}function M(a){return new Promise(function(b){L(a,b)})}function N(a){for(;a.firstChild;)a.removeChild(a.firstChild)};function O(a){return a.ampExtendedElements?!!a.ampExtendedElements["amp-bind"]:!1}function P(a){var b=E(a),c=J(F(a));return c?c:Promise.resolve().then(function(){return O(b.win)?I(F(a)):b.whenBodyAvailable().then(function(){return O(b.win)?I(F(a)):null})})}function Q(a){var b=B(a,"bind");return b?Promise.resolve(b):a.nodeType?(b=(a.ownerDocument||a).defaultView,b!==(b.__AMP_TOP||b)?R(b):P(a)):Promise.resolve(null)}
function R(a){return Promise.resolve().then(function(){return O(a)?I(a):M(a.document).then(function(){return O(a)?I(a):null})})};function S(a){var b={bubbles:!0},c={detail:null};Object.assign(c,b);if("function"==typeof a.CustomEvent)return new a.CustomEvent("amp:dom-update",c);a=a.document.createEvent("CustomEvent");a.initCustomEvent("amp:dom-update",!!c.bubbles,!!c.cancelable,null);return a};function T(a,b,c){var d=this;this.F=G(a,"timer");this.J=b;this.I=c||0;this.m=-1;this.A=0;this.B=!1;this.G=function(){d.m=-1;d.A=0;d.B=!0;d.J();d.B=!1}}T.prototype.isPending=function(){return-1!=this.m};T.prototype.schedule=function(a){var b=a||this.I;this.B&&10>b&&(b=10);var c=Date.now()+b;return!this.isPending()||-10>c-this.A?(this.cancel(),this.A=c,this.m=this.F.delay(this.G,b),!0):!1};T.prototype.cancel=function(){this.isPending()&&(this.F.cancel(this.m),this.m=-1)};function U(a,b,c,d){c=void 0===c?".":c;d=void 0===d?0:d;var e=z(b.getAttribute("src"),b),h=B(a,"url-replace",!0),l=1<=d?h.expandUrlAsync(e):Promise.resolve(e);return l.then(function(c){1==d&&h.collectUnwhitelistedVars(b).then(function(a){if(0<a.length){var c=b.tagName;k().error(c,"URL variable substitutions in CORS fetches triggered by amp-bind will soon require opt-in. Please add "+('data-amp-replace="'+a.join(" ")+'" to the ')+("<"+c+'> element. See "bit.ly/amp-var-subs" for details.'));m().expectedError(c,
"amp-bind CORS fetch without opt-in!")}});var e={};b.hasAttribute("credentials")?e.credentials=b.getAttribute("credentials"):e.requireAmpResponseSourceOrigin=!1;return G(a.win,"batched-xhr").fetchJson(c,e)}).then(function(a){return a.json()}).then(function(a){if(null==a)throw Error("Response is undefined.");var b;b=c||".";if("."!=b){b=b.split(".");for(var d=0;d<b.length;d++){var e=b[d];if(e&&a&&void 0!==a[e]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,e)))a=a[e];else{a=
void 0;break}}}b=a;return b})};function V(a){var b;b=AMP.BaseElement.call(this,a)||this;b.h=null;b.o=!1;b.D=new T(b.win,function(){return W(b)});b.l=null;b.K=G(b.win,"templates");b.w=!1;b.C=null;b.registerAction("refresh",function(){b.w&&X(b)},100);return b}f(V,AMP.BaseElement);V.prototype.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a||"intrinsic"==a};
V.prototype.buildCallback=function(){this.C=this.element.getAttribute("src");this.h=this.win.document.createElement("div");this.applyFillContent(this.h,!0);this.element.appendChild(this.h);this.h.hasAttribute("role")||this.h.setAttribute("role","list");this.element.hasAttribute("aria-live")||this.element.setAttribute("aria-live","polite")};V.prototype.reconstructWhenReparented=function(){return!1};V.prototype.layoutCallback=function(){this.w=!0;return X(this)};
V.prototype.mutatedAttributesCallback=function(a){var b=a.src,c=a.state;if(void 0!==b){var d=typeof b;if("string"===d)this.w&&X(this);else if("object"===d){var e=Array.isArray(b)?b:[b];Y(this,e);this.element.setAttribute("src","")}else this.user().error("amp-list",'Unexpected "src" type: '+b)}else void 0!==c&&(b=Array.isArray(c)?c:[c],Y(this,b),k().error("amp-list","[state] is deprecated, please use [src] instead."))};V.prototype.isLoadingReused=function(){return!0};
function Z(a,b){b?a.getVsync().mutate(function(){a.toggleFallback(!0);a.o=!0}):a.o&&a.getVsync().mutate(function(){a.toggleFallback(!1);a.o=!1})}
function X(a){if(!a.element.getAttribute("src"))return Promise.resolve();a.element.hasAttribute("reset-on-refresh")&&(a.togglePlaceholder(!0),a.toggleLoading(!0),Z(a,!1),N(a.h));var b=a.element.getAttribute("items")||"items";return aa(a,b).then(function(c){a.element.hasAttribute("single-item")&&(k().assert("undefined"!==typeof c,'Response must contain an array or object at "%s". %s',b,a.element),Array.isArray(c)||(c=[c]));k().assert(Array.isArray(c),'Response must contain an array at "%s". %s',b,
a.element);var d=parseInt(a.element.getAttribute("max-items"),10);d<c.length&&(c=c.slice(0,d));return Y(a,c)},function(a){throw k().createError("Error fetching amp-list",a);}).then(function(){a.getFallback()&&Z(a,!1);a.togglePlaceholder(!1);a.toggleLoading(!1)},function(b){a.toggleLoading(!1);if(a.getFallback())Z(a,!0),a.togglePlaceholder(!1);else throw b;})}function Y(a,b){var c,d,e=new Promise(function(a,b){c=a;d=b});a.l||a.D.schedule();a.l={items:b,resolver:c,rejecter:d};return e}
function W(a){function b(){a.l!==c?a.D.schedule(1):a.l=null}var c=a.l;a.K.findAndRenderTemplateArray(a.element,c.items).then(function(b){return ba(a,b)}).then(function(b){return ca(a,b)}).then(function(){b();c.resolver()},function(){b();c.rejecter()})}function ba(a,b){function c(){return b}return Q(a.element).then(function(c){if(c)return c.scanAndApply(b,[a.h])}).then(c,c)}
function ca(a,b){N(a.h);b.forEach(function(b){b.hasAttribute("role")||b.setAttribute("role","listitem");a.h.appendChild(b)});b=S(a.win);a.h.dispatchEvent(b);a.getVsync().measure(function(){var b=a.h.scrollHeight;b>a.element.offsetHeight&&a.attemptChangeHeight(b).catch(function(){})})}function aa(a,b){var c=a.getAmpDoc(),d=a.element.getAttribute("src"),e=1;if(d==a.C||x(A(d)).origin==x(A(c.win.location)).origin)e=2;return U(c,a.element,b,e)}(function(a){a.registerElement("amp-list",V)})(self.AMP);
})});
//# sourceMappingURL=amp-list-0.1.js.map

