(self.AMP=self.AMP||[]).push({n:"amp-position-observer",v:"1524862012167",f:(function(AMP){function l(a,b){function d(){}d.prototype=b.prototype;a.prototype=new d;a.prototype.constructor=a;for(var c in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c]};self.log=self.log||{user:null,dev:null,userForEmbed:null};var m=self.log;function n(){if(!m.user)throw Error("failed to call initLogConstructor");return m.user};function p(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView;if(b=b!=(b.__AMP_TOP||b)&&q(b,"action")?r(b,"action"):null)return b}return t(a,"action")}function u(a,b){var d=v(a),c=w(d);a=c;var e=x(a),f=e["position-observer"];f||(f=e["position-observer"]={obj:null,promise:null,resolve:null,context:null,ctor:null});f.ctor||f.obj||(f.ctor=b,f.context=d,f.resolve&&r(a,"position-observer"))}function y(a,b){a=a.__AMP_TOP||a;return r(a,b)}function t(a,b){a=v(a);a=w(a);return r(a,b)}
function v(a){return a.nodeType?y((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function w(a){a=v(a);return a.isSingleDoc()?a.win:a}function r(a,b){q(a,b);var d=x(a);a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function x(a){var b=a.services;b||(b=a.services={});return b}function q(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function z(a,b,d){var c,e={detail:d};Object.assign(e,c);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,d);return a};function A(a){n().assert(/^\d+(\.\d+)?(px|em|rem|vh|vw|vmin|vmax|cm|mm|q|in|pc|pt)$/.test(a),"Invalid length value: %s",a);return a};function B(a,b,d,c){return{left:a,top:b,width:d,height:c,bottom:b+c,right:a+d,x:a,y:b}}function C(a,b){return a.top<b.top?"top":a.bottom>b.bottom?"bottom":"inside"}function D(a,b){return a&&b?a.left==b.left&&a.top==b.top&&a.width==b.width&&a.height==b.height:!1};function E(a,b){function d(){c=0;var h=500-(a.Date.now()-e);if(0<h)c=a.setTimeout(d,h);else{var g=f;f=null;b.apply(null,g)}}var c=0,e=0,f=null;return function(b){for(var h=[],k=0;k<arguments.length;++k)h[k-0]=arguments[k];e=a.Date.now();f=h;c||(c=a.setTimeout(d,500))}};function F(a,b,d,c){this.element=b;this.N=c;this.fidelity=d;this.turn=0==d?Math.floor(4*Math.random()):0;this.w=null;this.l=t(a,"viewport")}
F.prototype.update=function(a){var b=this;if(!a){if(0!=this.turn){this.turn--;return}0==this.fidelity&&(this.turn=4)}var d=this.l.getSize(),c=B(0,0,d.width,d.height);this.l.getClientRectAsync(this.element).then(function(a){var d={positionRect:a,viewportRect:c,relativePos:""},e=b.w;if(!(e&&D(e.positionRect,d.positionRect)&&D(e.viewportRect,d.viewportRect))){e=d.positionRect;d.relativePos=C(e,d.viewportRect);var g=d.viewportRect;e.top<=g.bottom&&g.top<=e.bottom&&e.left<=g.right&&g.left<=e.right?(b.w=
d,b.N(d)):b.w&&(b.w=null,d.positionRect=null,b.N(d))}})};function G(a){var b=this;this.R=a;this.P=a.win;this.h=[];this.V=y(this.P,"vsync");this.l=t(a,"viewport");this.D=[];this.H=this.J=this.I=!1;this.S=E(this.P,function(){b.I=!1})}G.prototype.observe=function(a,b,d){var c=new F(this.R,a,b,d);this.h.push(c);this.H||H(this);c.update()};
G.prototype.unobserve=function(a){for(var b=0;b<this.h.length;b++)if(this.h[b].element==a){this.h.splice(b,1);if(0==this.h.length)for(this.H=!1;this.D.length;)this.D.pop()();return}if(m.dev)a=m.dev;else throw Error("failed to call initLogConstructor");a.error("POSITION_OBSERVER","cannot unobserve unobserved element")};function H(a){a.H=!0;a.D.push(a.l.onScroll(function(){a.S();a.I=!0;a.J||I(a)}));a.D.push(a.l.onResize(function(){a.updateAllEntries(!0)}))}
G.prototype.updateAllEntries=function(a){for(var b=0;b<this.h.length;b++)this.h[b].update(a)};function I(a){a.updateAllEntries();a.J=!0;a.I?a.V.measure(function(){I(a)}):a.J=!1}function J(a){u(a,function(){return new G(a)})};function K(a){a=AMP.BaseElement.call(this,a)||this;a.m=null;a.c=!1;a.K=null;a.C=0;a.j=0;a.M="0";a.G="0";a.A=0;a.O=0;a.F=null;a.B=null;a.o=null;a.L=0;return a}l(K,AMP.BaseElement);K.prototype.isLayoutSupported=function(a){return"nodisplay"==a};K.prototype.buildCallback=function(){var a=t(this.getAmpDoc(),"viewer");a.whenFirstVisible().then(this.T.bind(this))};
K.prototype.T=function(){var a=this;L(this);this.m=p(this.element);this.K||(J(this.getAmpDoc()),this.K=t(this.getAmpDoc(),"position-observer"));this.getAmpDoc().whenReady().then(function(){var b;b=a.B?n().assertElement(a.getAmpDoc().getElementById(a.B),"No element found with id:"+a.B):a.element.parentNode;a.getAmpDoc().getBody()==b&&(b=a.win.document.documentElement);var d=b;a.K.observe(d,1,a.U.bind(a))})};
function M(a){var b=z(a.win,"amp-position-observer.scroll",{percent:a.L});a.m.trigger(a.element,"scroll",b,1)}
K.prototype.U=function(a){var b=this.c,d=this.F&&this.F.height,c=a;this.o||(this.o=c.viewportRect.height);var e=this.o-c.viewportRect.height,f=0;150>Math.abs(e)?f=e:this.o=null;c.viewportRect=B(c.viewportRect.left,c.viewportRect.top,c.viewportRect.width,c.viewportRect.height+f);this.F=a.viewportRect;d!=a.viewportRect.height&&(this.A=N(this,this.M),this.O=N(this,this.G));var c=a.viewportRect,h=c=B(c.left,c.top+this.A,c.width,c.height-this.O-this.A),c=a.positionRect,g;if(c)if(g=C(c,h),e=h,f=g,"inside"==
f)this.c=!0;else{var k=c.height*("top"==f?this.C:this.j);this.c="bottom"==f?c.top<=e.bottom-k:c.bottom>=e.top+k}else this.c=!1,g=a.relativePos;b&&!this.c&&(this.L="bottom"==g?0:1,M(this),e=z(this.win,"amp-position-observer.exit",{}),this.m.trigger(this.element,"exit",e,1));!b&&this.c&&(e=z(this.win,"amp-position-observer.enter",{}),this.m.trigger(this.element,"enter",e,1));this.c&&(e=h,c&&(this.L=Math.abs(c.top-this.A-(e.height-c.height*this.j))/(e.height+c.height-(c.height*this.j+c.height*this.C))),
M(this))};function L(a){var b=a.element.getAttribute("intersection-ratios");if(b){var d=b.trim().split(" ");a.C=O(d[0]);a.j=a.C;d[1]&&(a.j=O(d[1]))}var c=a.element.getAttribute("viewport-margins");c&&(c=c.trim().split(" "),a.M=c[0],a.G=a.M,c[1]&&(a.G=c[1]));a.B=a.element.getAttribute("target")}
function N(a,b){b="number"==typeof b?b+"px":b&&/^\d+(\.\d+)?(px|em|rem|vh|vw|vmin|vmax|cm|mm|q|in|pc|pt)?$/.test(b)?/^\d+(\.\d+)?$/.test(b)?b+"px":b:void 0;var d=b=A(b);A(d);var d=n().assert(d.match(/[a-z]+/i),"Failed to read units from %s",d)[0],c;c=parseFloat(b);c="number"===typeof c&&isFinite(c)?c:void 0;if(!c)return 0;n().assert("px"==d||"vh"==d,"Only pixel or vh are valid as units for exclusion margins: "+b);"vh"==d&&(c=c/100*a.F.height);return c}
function O(a){var b=parseFloat(a);n().assert(0<=b&&1>=b,"Ratios must be a decimal between 0 and 1: "+a);return b}(function(a){a.registerElement("amp-position-observer",K)})(self.AMP);
})});
//# sourceMappingURL=amp-position-observer-0.1.js.map

